### ISSUE TITLE
mregions2: Access Data from Marineregions.org: The Marine Regions Gazetteer and the Marine Regions Data Products

### ISSUE THREAD

**Issue by salvafern** [ropensci/software-review#590] opened 2023-04-26 14:20 UTC
**Date accepted:** 2024-06-09

Submitting Author Name: Salvador Fernández Bejarano
Submitting Author Github Handle: @salvafern
Other Package Authors Github handles: (comma separated, delete if none) @lottepohl
Repository:  https://github.com/lifewatch/mregions2
Version submitted: 
Submission type: Standard
Editor: @jooolia
Reviewers: @Kattuvan, @sheilasaia
Due date for @Kattuvan: 2023-06-20
Due date for @sheilasaia: 2023-06-21
Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: mregions2
Type: Package
Title: Access Data from Marineregions.org: The Marine Regions Gazetteer and the Marine Regions Data Products
Version: 1.0.0
Authors@R: c(
  person(given = "Salvador", family = "Fernandez-Bejarano", role = c("aut", "cre"),
         email = "salvador.fernandez@vliz.be",
         comment = c(ORCID = "0000-0003-0535-7677", github = "salvafern")),
  person(given = "Lotte",family = "Pohl", role = "aut",
         email = "lotte.pohl@imbrsea.eu",
         comment = c(ORCID = "0000-0002-7607-7018", github = "whaleshark99")),
  person("LifeWatch Belgium", role = "fnd", comment = "https://lifewatch.be")
  )
Maintainer: Salvador Fernandez-Bejarano <salvador.fernandez@vliz.be>
Description: Explore and retrieve marine geo-spatial data from the Marine Regions Gazetteer and the Marine Regions Data Products, including the Maritime Boundaries.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Config/testthat/edition: 3
Imports: 
    checkmate,
    glue,
    httr2,
    magrittr,
    sf,
    utils,
    rdflib,
    ISOcodes,
    memoise,
    cli,
    dplyr,
    xml2,
    wrapr,
    methods,
    curl,
    digest
RoxygenNote: 7.2.0
URL: https://github.com/lifewatch/mregions2,
    https://lifewatch.github.io/mregions2/
BugReports: https://github.com/lifewatch/mregions2/issues
Suggests: 
    ows4R (>= 0.3),
    httptest2,
    jsonlite,
    knitr,
    leaflet,
    leaflet.extras2,
    mapview,
    mregions,
    rmarkdown,
    testthat,
    wk,
    purrr,
    withr
VignetteBuilder: knitr
Roxygen: list(markdown = TRUE)
Depends: 
    R (>= 2.10)

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):
	- [x] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

This package reads the [Marine Regions Gazetteer](https://marineregions.org/gazetteer.php) and the [Marine Regions Data Products](https://marineregions.org/sources.php) via a REST API and OGC web services respectively. The data is mostly geospatial as it contains locations of marine places in the world.

-   Who is the target audience and what are scientific applications of this package?

The main purpose of Marine Regions is to serve as the geographical backbone of biodiversity databases such as WoRMS or EurOBIS, hence the main user will be scientists that want to geo-reference their research. But it can also be useful for industry, policy and law makers. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There is already a package to read Marine Regions. The need for this second package is explained in one of the package's articles: [Why mregions2?](https://lifewatch.github.io/mregions2/articles/why_mregions2.html) . It was also discussed beforehand that a new package was the best approach: https://github.com/ropensci/mregions/pull/62 (Mostly to not break compatibility)

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

In general I think this does not apply. The only data being collected from users is the user-agent in all HTTP requests. This gets the environment variable `HTTPUserAgent` via `getOption()` in [mr_user_agent](https://github.com/lifewatch/mregions2/blob/9ed0de6db99b2415400ecc6f8d0df2f5b1577fef/R/utils.R#L48)

On the other hand, Marine Regions has sensitive data products such as the maritime boundaries. It is stated clearly on our [disclaimer](https://www.marineregions.org/disclaimer.php) that the data has no legal value whatsoever. 

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.
-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by maurolepore** [comment] 2023-04-26 17:37
Thanks @salvafern for this submission and for pointing to https://github.com/ropensci/mregions/pull/62. 

How can we leave a record that the maintainer of mregions is OK with the decision of submitting mregions2? Maybe you can point me to an GH-issue comment?

**Comment by salvafern** [comment] 2023-04-27 08:01
Hi @maurolepore, thanks for checking out! 🚀 

I am actually the current maintainer of mregions (https://github.com/ropensci/mregions/commit/e5fb45be93a957e4ccc51158bb900f72dbcd08a1). Before me were @LennertSchepers and @sckott (https://github.com/ropensci/mregions/commit/dd7b6e44aef74808f3f0f75a09d0568356ce632d). 

Since we had this public conversation on https://github.com/ropensci/mregions/pull/62, and also got the idea of a new package from @maelle (see https://github.com/ropensci/mregions/pull/62#issuecomment-1061969979), I think we are all on the same page about submitting mregions2. But if there is any objection from Lennert or Scott I'm happy to discuss of course 😃

**Comment by sckott** [comment] 2023-04-27 15:56
No objection from me

**Comment by LennertSchepers** [comment] 2023-04-28 08:48
No objection from me, @salvafern is in our team so we discussed the whole process in detail.

**Comment by LennertSchepers** [comment] 2023-04-28 09:32
Worth noting if you need written approval: we are also the Marine Regions data system developers/maintainers/owners (see e.g. https://marineregions.org/editors.php)

**Comment by maurolepore** [comment] 2023-04-30 16:45
Thanks @salvafern and everyone else for your support. 
I'll stat searching for a handling editor.

**Comment by maelle** [comment] 2023-05-02 09:55
@ropensci-review-bot assign @jooolia as editor

**Comment by jooolia** [comment] 2023-05-05 14:00
### Editor checks:

- [X] **Documentation**: The package has sufficient documentation available online (README, pkgdown docs) to allow for an assessment of functionality and scope without installing the package. In particular,
    - [X] Is the case for the package well made?
    - [X] Is the reference index page clear (grouped by topic if necessary)?
    - [X] Are vignettes readable, sufficiently detailed and not just perfunctory?
- [X] **Fit**: The package meets criteria for [fit](https://devguide.ropensci.org/policies.html#package-categories) and [overlap](https://devguide.ropensci.org/policies.html#overlap).
- [X] **Installation instructions:** Are installation instructions clear enough for human users?
- [X] **Tests**: If the package has some interactivity / HTTP / plot production etc. are the tests using [state-of-the-art tooling](https://devguide.ropensci.org/building.html#testing)?
    - Yes httptest2
- [ ] **Contributing information**: Is the documentation for contribution clear enough e.g. tokens for tests, playgrounds?

    - .github/CONTRIBUTING.md exists, but only gives detail to email one of the authors and to abide by the Code of Conduct rules. I think this could be improved with resources contained here: https://devguide.ropensci.org/collaboration.html?q=contribu#contributing-guide

- [X] **License:** The package has a CRAN or OSI accepted license.
- [X] **Project management**: Are the issue and PR trackers in a good shape, e.g. are there outstanding bugs, is it clear when feature requests are meant to be tackled?
Github action checks are kept open as issues, one for each branch. 
---

#### Editor comments

Dear @salvafern and @whaleshark99, 

Thanks for your submission. Overall the package is in great shape. The only thing that I would note would that it would be even better with more information on how to contribute to the package. Feel free to let me know if there is a reason that additional info should not be added. I will start looking for reviewers. 

Cheers, Julia

---

**Comment by jooolia** [comment] 2023-05-26 09:19
Hello, I am still actively looking for reviewers. Thanks, Julia

**Comment by Kattuvan** [comment] 2023-05-30 02:47
@jooolia I accept your invitation to review it. This is my first attempt to review a package. 
Do you have a Test Case   to look for bugs. 
Do I have to get a data frame to test all those 30 functions/methods

**Comment by Kattuvan** [comment] 2023-05-30 02:52
@jooolia I found the guidelines  https://devguide.ropensci.org/reviewerguide.html
I am sorry for my earlier mail

**Comment by jooolia** [comment] 2023-05-30 18:27
@ropensci-review-bot assign @Kattuvan as reviewer

**Comment by jooolia** [comment] 2023-05-30 18:28
Thanks @Kattuvan for agreeing to review! Glad that you found the guide. :)

**Comment by jooolia** [comment] 2023-05-31 03:36
@ropensci-review-bot assign @sheilasaia as reviewer

**Comment by jooolia** [comment] 2023-05-31 03:37
Thanks @sheilasaia for agreeing to review. Please feel free to reach out if you have any questions. Thanks, Julia

**Comment by Kattuvan** [comment] 2023-06-05 02:40
Hi Julia,
Please find below the results I obtained using the 'pkgcheck'  on 'mregions2'.
Are you expecting me to use the package against the data for further check.
This is my first review of any package. I appreciate your guidance. Thanks
Murali.


> summary(x)

── mregions2 1.0.0 ──────────────────────────────────────────────────────────────

✔ Package name is available
✔ has a 'codemeta.json' file.
✔ has a 'contributing' file.
✔ uses 'roxygen2'.
✔ 'DESCRIPTION' has a URL field.
✔ 'DESCRIPTION' has a BugReports field.
✔ Package has at least one HTML vignette
✔ All functions have examples.
✖ Package has no continuous integration checks.
✔ Package coverage is 91.5%.
✖ R CMD check found 1 error.
✖ R CMD check found 1 warning.

ℹ Current status:
✖ This package is not ready to be submitted.

> print(x)

── mregions2 1.0.0 ──────────────────────────────────────────────────────────────

✔ Package name is available
✔ has a 'codemeta.json' file.
✔ has a 'contributing' file.
✔ uses 'roxygen2'.
✔ 'DESCRIPTION' has a URL field.
✔ 'DESCRIPTION' has a BugReports field.
✔ Package has at least one HTML vignette
✔ All functions have examples.
✖ Package has no continuous integration checks.
✔ Package coverage is 91.5%.
✖ R CMD check found 1 error.
✖ R CMD check found 1 warning.

ℹ Current status:
✖ This package is not ready to be submitted.


── git ──

• HEAD: 9ed0de6d
• Default branch: main
• Number of commits: 134
• First commit: 27-04-2022
• Number of authors: 3


── Package Structure ──

ℹ Package uses the following languages:
• : %

ℹ Package has
• 2 authors.
• 3 vignettes.
• 1 internal data file.
• 16 imported packages.
• 59 exported functions (median 3 lines of code).
• 123 non-exported functions (median 6 lines of code).
• 2 parameters per function (median).

── Package statistics ──

                   measure  value percentile noteworthy
1                  files_R    0.0        0.0       TRUE
4          files_vignettes    0.0        0.0       TRUE
5              files_tests    0.0        0.0       TRUE
6            num_vignettes    3.0       94.2           
7          data_size_total 7328.0       69.2           
8         data_size_median 7328.0       77.0           
9                  n_fns_r  182.0       88.4           
10        n_fns_r_exported   59.0       90.2           
11    n_fns_r_not_exported  123.0       87.4           
12        n_fns_per_file_r   10.2       87.7           
13       num_params_per_fn    2.0       11.9           
14            loc_per_fn_r    5.0        8.1           
15        loc_per_fn_r_exp    3.0        1.5       TRUE
16    loc_per_fn_r_not_exp    6.0       13.8           
17     doclines_per_fn_exp   55.0       68.4           
18 doclines_per_fn_not_exp    0.0        0.0       TRUE
19    fn_call_network_size  100.0       79.2           

ℹ Package network diagram is at [C:/Users/Murali/AppData/Local/Cache/R/pkgcheck/static/mregions2_pkgstats9ed0de6d.html].


── goodpractice ──

── GP mregions2 ─────────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code in
    general. 91% of code lines are covered by test cases.

    R/00_gaz_geom.R:54:NA
    R/00_gaz_geom.R:338:NA
    R/00_gaz_geom.R:339:NA
    R/00_gaz_geom.R:340:NA
    R/00_gaz_geom.R:341:NA
    ... and 71 more lines

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    data-raw\mrp_list.R:20:81
    R\00_gaz_geom.R:6:81
    R\00_gaz_geom.R:9:81
    R\00_gaz_geom.R:10:81
    R\00_gaz_geom.R:13:81
    ... and 387 more lines

  ✖ fix this R CMD check NOTE: Note: found 1 marked UTF-8
    string
  ✖ fix this R CMD check WARNING: LaTeX errors when creating
    PDF version. This typically indicates Rd problems.
───────────────────────────────────────────────────────────────────────────────── 
── Package Versions ──

  pkgstats: 0.1.3.4
  pkgcheck: 0.1.1.24
> results_of_x <- print(x)

── mregions2 1.0.0 ──────────────────────────────────────────────────────────────

✔ Package name is available
✔ has a 'codemeta.json' file.
✔ has a 'contributing' file.
✔ uses 'roxygen2'.
✔ 'DESCRIPTION' has a URL field.
✔ 'DESCRIPTION' has a BugReports field.
✔ Package has at least one HTML vignette
✔ All functions have examples.
✖ Package has no continuous integration checks.
✔ Package coverage is 91.5%.
✖ R CMD check found 1 error.
✖ R CMD check found 1 warning.

ℹ Current status:
✖ This package is not ready to be submitted.


── git ──

• HEAD: 9ed0de6d
• Default branch: main
• Number of commits: 134
• First commit: 27-04-2022
• Number of authors: 3


── Package Structure ──

ℹ Package uses the following languages:
• : %

ℹ Package has
• 2 authors.
• 3 vignettes.
• 1 internal data file.
• 16 imported packages.
• 59 exported functions (median 3 lines of code).
• 123 non-exported functions (median 6 lines of code).
• 2 parameters per function (median).

── Package statistics ──

                   measure  value percentile noteworthy
1                  files_R    0.0        0.0       TRUE
4          files_vignettes    0.0        0.0       TRUE
5              files_tests    0.0        0.0       TRUE
6            num_vignettes    3.0       94.2           
7          data_size_total 7328.0       69.2           
8         data_size_median 7328.0       77.0           
9                  n_fns_r  182.0       88.4           
10        n_fns_r_exported   59.0       90.2           
11    n_fns_r_not_exported  123.0       87.4           
12        n_fns_per_file_r   10.2       87.7           
13       num_params_per_fn    2.0       11.9           
14            loc_per_fn_r    5.0        8.1           
15        loc_per_fn_r_exp    3.0        1.5       TRUE
16    loc_per_fn_r_not_exp    6.0       13.8           
17     doclines_per_fn_exp   55.0       68.4           
18 doclines_per_fn_not_exp    0.0        0.0       TRUE
19    fn_call_network_size  100.0       79.2           

ℹ Package network diagram is at [C:/Users/Murali/AppData/Local/Cache/R/pkgcheck/static/mregions2_pkgstats9ed0de6d.html].


── goodpractice ──

── GP mregions2 ─────────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code in
    general. 91% of code lines are covered by test cases.

    R/00_gaz_geom.R:54:NA
    R/00_gaz_geom.R:338:NA
    R/00_gaz_geom.R:339:NA
    R/00_gaz_geom.R:340:NA
    R/00_gaz_geom.R:341:NA
    ... and 71 more lines

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    data-raw\mrp_list.R:20:81
    R\00_gaz_geom.R:6:81
    R\00_gaz_geom.R:9:81
    R\00_gaz_geom.R:10:81
    R\00_gaz_geom.R:13:81
    ... and 387 more lines

  ✖ fix this R CMD check NOTE: Note: found 1 marked UTF-8
    string
  ✖ fix this R CMD check WARNING: LaTeX errors when creating
    PDF version. This typically indicates Rd problems.
───────────────────────────────────────────────────────────────────────────────── 
── Package Versions ──

  pkgstats: 0.1.3.4
  pkgcheck: 0.1.1.24
    On Tuesday, May 30, 2023 at 11:37:37 p.m. EDT, Julia Gustavsen ***@***.***> wrote:  
 
 


Thanks @sheilasaia for agreeing to review. Please feel free to reach out if you have any questions. Thanks, Julia

**Comment by jooolia** [comment] 2023-06-05 06:16
Dear @Kattuvan , Great that you ran {pkgcheck}, will you follow up with the [review template](https://devguide.ropensci.org/reviewtemplate.html#reviewtemplate) ? Here there are specific things to check and an opportunity to provide your comments on the package to the authors (related to the code, the usability and functionality). Thanks, Julia

**Comment by Kattuvan** [comment] 2023-06-07 02:22
Hi Julia,
Please find attached duly filled review template herewith.
Thank you.
Murali
    On Monday, June 5, 2023 at 02:16:43 a.m. EDT, Julia Gustavsen ***@***.***> wrote:  
 
 


Dear @Kattuvan , Great that you ran {pkgcheck}, will you follow up with the review template ? Here there are specific things to check and an opportunity to provide your comments on the package to the authors (related to the code, the usability and functionality). Thanks, Julia

**Comment by jooolia** [comment] 2023-06-09 06:38
Hi @Kattuvan, thanks for the doing the review. I think you may have attached something via email, but this did not appear on Github. Could you paste your review directly in the issue by logging into Github? 
Thanks, Julia

**Comment by Kattuvan** [comment] 2023-06-11 21:29
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   **Briefly describe any working relationship you have (had) with the package authors.**
-   ☒ As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

#### Documentation

The package includes all the following forms of documentation:

-   ☒ **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README

-   ☒ **Installation instructions:** for the development version of package and any non-standard dependencies in README

-   dependencies ‘sf’; ‘dplyr’; ‘magritter’ are referenced elsewhere. <https://lifewatch.github.io/mregions2/articles/mregions2.html/>

-   ☒ **Vignette(s):** demonstrating major functionality that runs successfully locally

-   Package has at least one HTML vignette

-   But Vignette is available only through 'READ.md' 

-   ☐ **Function Documentation:** for all exported functions

-   ☒ **Examples:** (that run successfully locally) for all exported functions

-   Examples don’t run in place.

-   All functions have examples

-   ☒ **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

-   availble

#### Functionality

-   ☒ **Installation:** Installation succeeds as documented.

-   Removed ‘sf’; ‘dplyr’; ‘magritter’ from local system to test installation of ‘mregion2’

-   I get error message “Error in loadNamespace(j &lt;- i\[\[1L\]\], c(lib.loc, .libPaths()), versionCheck = vI\[\[j\]\]) : there is no package called ‘magrittr’”

-   So, I installed ‘magrittr’ before attempting again ‘mregion2’

-   ‘mregions2’ installs dependencies ‘sf’ and ‘dplyr’

-   ☐ **Functionality:** Any functional claims of the software been confirmed.

-   ☐ **Performance:** Any performance claims of the software been confirmed.

-   ☒ **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.

-   It is good practice to write unit tests for all functions, and all package code in general. 91% of code lines are covered by test cases.

-   avoid long code lines, it is bad for readability. Also, many people prefer editor windows that are about 80 characters wide. Try make your lines shorter than 80 characters

-   ☒ **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

-   This package is not ready to be submitted.

-   Package has no continuous integration checks.

Estimated hours spent reviewing: 16 Hours

-   ☒ Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer (“rev” role) in the package DESCRIPTION file.

------------------------------------------------------------------------

### Review Comments

**Comment by Kattuvan** [comment] 2023-06-11 21:31
Hi Julia,
Done it as your requirements.
Murali
    On Friday, June 9, 2023 at 02:38:32 a.m. EDT, Julia Gustavsen ***@***.***> wrote:  
 
 


Hi @Kattuvan, thanks for the doing the review. I think you may have attached something via email, but this did not appear on Github. Could you paste your review directly in the issue by logging into Github?
Thanks, Julia

**Comment by jooolia** [comment] 2023-06-16 06:26
Hi @Kattuvan 
Thanks for using the template. Do you have any comments overall to accompany your review or any comments on specific lines of code? Thanks, Julia

**Comment by sheilasaia** [comment] 2023-06-25 15:41
Here's my review.

## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [X] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all exported functions
- [X] **Examples:** (that run successfully locally) for all exported functions
- [X] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [X] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 4 hours

- [X] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

Overall comments:

This package enables folks to directly access two specific datasets directly in their R session. I'm not familiar with the specific datasets myself, but can see how this would be helpful and a unique contribution to the R package space. I didn't have any problems with installing the package and all the lines of code in the vignette worked well including the leaflet maping functions. That said, there are several things that I think still need to be addressed before the package can be submitted.

I left some specific comments below. Thanks for the opportunity to review this rOpenSci package submission!

Some specific comments:

- I suggest you list the current maintainer on the GitHub page "About" section on the right (https://github.com/lifewatch/mregions2). I don't see that there, currently, but do see it in the DESCRIPTION file.
- I see there's an MIT licence file (license.md) given but this is not connected to the "About" section on the right of the main GitHub page. I suggest fixing the link to that file and also spelling out the specific author names directly in the license file so that's clear. It's currently listed as "authors".
- The code of conduct and citations files look complete.
- Can the authors give a little bit more info about the audience of this package in the description at the very top of the readme? It would be helpful to have a sentence or two at the very top that directly explains what types of data are in the Marine Regions Gazetteer and Marine Regions Data Products for those that are not familiar with these resources and would like to know this from quickly scanning the readme.
- Can the authors use the example in the R script for `gaz_search()`? Specifically it was `gaz_search("Belgian Part of the North Sea")`. When I first looked at this function in the vignette I mistook the input as having to only be a country so an example of what you all mean by "free text" would be helpful to see.
- When I run `gaz_rest()` I don't get a help page. I get an error that it cannot find the function: "Error in gaz_rest() : could not find function "gaz_rest"" I tried running without the `()` at the end and am also getting an error.
- In the usage description of `mrp_view()` please explain that all the functions under `mrp_view()` are for specific layers in the mrp data file. Maybe include a sub heading such as "Specific Layer Usage" or something similar to that to make this clear.
- The authors don't have a vignette for `mrp_col_unique()` but it would be helpful to include this since it can give the user a sense of what columns are available to them if they are not as familiar with the structure of the Marine Regions data product.
- The line `gaz_search_by_type("EEZ")` was taking me 13 seconds to run, which is still fast, but longer than the other functions were taking (i.e., generally most took 1-2 sections). I wanted to let the authors know this in case that's unexpected.
- It would be helpful to have a section in the bottom of the README that discusses whether there are similar packages or maybe even complimentary packges to this one. That way the user get get a quick background.
- According to the ropensci-review-bot, it looks like only 91% of the functions are covered by tests so I suggest the authors work on this so the package is 100% covered.

**Comment by salvafern** [comment] 2023-06-26 12:43
Hi all,

Thank you very much @jooolia for coordinating the reviews; and @Kattuvan and @sheilasaia for your thorough reviews!

I'm currently the solely developer of mregions2 and I'm also going on leave soon till 2023-07-24, thus won't be able to address the reviews until then. Hope this is not a problem, otherwise I will try to find someone who can pick this up during my absence.

**Comment by jooolia** [comment] 2023-06-30 08:53
Hi @salvafern,
Thanks for letting us know. That is fine, talk to you when you are back.
Cheers, Julia

**Comment by jooolia** [comment] 2023-09-13 07:16
Hi @salvafern,
Hope that you are well. Do you have any updates on your progress?
Thanks, Julia

**Comment by salvafern** [comment] 2023-09-13 11:43
Hi @jooolia

Yes I am currently addressing the reviews (see https://github.com/lifewatch/mregions2/issues/1#issuecomment-1710318418 , will be updating the comment). 
Apologies for the delay, I haven't been able to allocate time before. I should be able to do most of the changes this week.

**Comment by sheilasaia** [comment] 2023-10-11 03:46
@salvafern, thanks for your replies! I will check back at my `gaz_rest` comment and get back to you with session info, hopefully by the end of the weekend.

**Comment by salvafern** [comment] 2023-10-23 15:15
Hi @sheilasaia, Indeed it was not that clear. The purpose of `gaz_rest` was to explain quickly why there are functions with names starting as `gaz_rest_*`. I think it is beneficial to keep this doc as I can easily link it to all `gaz_rest_*` functions through the section @ seealso  . I improved the explanations now (https://github.com/lifewatch/mregions2/commit/a86a1d4ad391bfb96d7f29171056fecda0568779). Let me know if it is better or you would still remove it from the docs.

**Comment by sheilasaia** [comment] 2023-10-24 01:43
Looks good to me, @salvafern! Thank you.

**Comment by jooolia** [comment] 2023-11-25 22:27
Hello @salvafern, sorry for the delay in my handling. I missed these updates. :( 
Thank you for all of the work!

**Comment by jooolia** [comment] 2023-11-25 22:28
Hi @Kattuvan,
Do you feel that the changes and updates have addressed your concerns? 
Thanks, Julia

**Comment by salvafern** [comment] 2024-02-22 13:44
Hi @jooolia, did you receive any message from @Kattuvan ? Any chance to move this submission forward?
Best, Salva

**Comment by Kattuvan** [comment] 2024-02-24 21:32
Hi,Please move the submission to the next level.
Regards,Murali
    On Thursday, February 22, 2024 at 08:44:27 a.m. EST, salvafern ***@***.***> wrote:  
 
 


Hi @jooolia, did you receive any message from @Kattuvan ? Any chance to move this submission forward?
Best, Salva

**Comment by salvafern** [comment] 2024-03-04 15:02
Hi @jooolia , please let me know if there is anything else I can do on my side to move this submission forward. 
Best, Salva

**Comment by jooolia** [comment] 2024-03-04 15:30
Dear Salva,

Sorry for the delay. I will get back to you at the latest by March 10th.
Thank you for your patience.

Cheers, Julia

**Comment by jooolia** [comment] 2024-03-10 21:05
Dear @salvafern, 
Things are looking good, although the comments about the CI have not fully been addressed in my view. I had a quick look, but the logs are too old (more than three months) to be viewed. Could you try re-running the Github Actions for the pkg-check and R-CMD-check so that we can help troubleshoot what is happening here?

Thanks!

**Comment by salvafern** [comment] 2024-04-09 13:01
Hi @jooolia, apologies for the delay. The logs are fresh now: https://github.com/lifewatch/mregions2/actions/runs/8615096758/job/23609894330

I think the same issue continues: See https://github.com/lifewatch/mregions2/issues/21 and https://github.com/ropensci/rdflib/issues/47

Any ideas are highly appreciated!

**Comment by jooolia** [comment] 2024-04-28 19:59
Thanks @salvafern for the reruns. I will have a look and get back to you (and it seems that rdflib has commented out the ubuntu tests for now). thanks, Julia

**Comment by jooolia** [comment] 2024-05-05 19:44
Hi @salvafern , I have forked mregions2 and will look into the github actions tomorrow. thanks for your patience.

**Comment by salvafern** [comment] 2024-05-06 08:43
That's great, thank you!

**Comment by jooolia** [comment] 2024-05-07 03:03
Hi @salvafern, I have gotten R-CMD-check to run without errors, although it is a bit of a workaround at the moment. I will look into the yaml files tonight and update you then (or if all goes well submit a pull request) with what has worked and what we could imagine doing. 
Cheers, Julia

**Comment by jooolia** [comment] 2024-05-20 09:24
Hi @salvafern I have opened a PR in the repo to your dev branch. Let me know what you think. I had to remove pkgcheck, but all three others I was able to get to work and pass. 
Cheers, Julia

**Comment by salvafern** [comment] 2024-06-03 09:45
Hi @jooolia , I have merge your PR to the main branch. Seems to work fine now. Thanks a lot! Let me know what are the next steps.

**Comment by jooolia** [comment] 2024-06-09 18:12
@ropensci-review-bot approve mregions2

**Closed by jooolia** 2024-06-09 18:12 UTC
Labels: 6/approved

**Comment by salvafern** [comment] 2024-06-17 09:34
@ropensci-review-bot invite me to ropensci/mregions2

**Comment by salvafern** [comment] 2024-06-17 09:44
@ropensci-review-bot finalize transfer of mregions2
