### ISSUE TITLE
dynamite: Bayesian Modeling and Causal Inference for Multivariate Longitudinal Data

### ISSUE THREAD

**Issue by santikka** [ropensci/software-review#554] opened 2022-08-18 13:33 UTC
**Date accepted:** 2022-12-13
Submitting Author Name: Santtu Tikka
Submitting Author Github Handle: @santikka
Other Package Authors Github handles: @helske
Repository:  https://github.com/santikka/dynamite
Version submitted: 0.0.1
Submission type: Stats
Badge grade: gold
Editor: @noamross
Reviewers: @nicholasjclark, @lucymcgowan
Due date for @nicholasjclark: 2022-09-27
Due date for @lucymcgowan: 2022-10-20
Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: dynamite
Title: Bayesian Modeling and Causal Inference for Multivariate
    Longitudinal Data
Version: 0.0.1
Authors@R: c(
    person("Santtu", "Tikka", , "santtuth@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0003-4039-4342")),
    person("Jouni", "Helske", , "jouni.helske@iki.fi", role = "aut",
           comment = c(ORCID = "0000-0001-7130-793X"))
  )
Description: Easy-to-use and efficient interface for 
  Bayesian inference of complex panel (time series) data. The package supports 
  joint modeling of multiple measurements per individual, time-varying and
  time-invariant effects, and a wide range of discrete and 
  continuous distributions. Estimation of the models is carried out via 'Stan'.
License: GPL (>= 3)
URL: https://github.com/santikka/dynamite
BugReports: https://github.com/santikka/dynamite/issues
Depends: 
    R (>= 4.1.0)
Imports: 
    bayesplot,
    checkmate,
    cli,
    data.table (>= 1.14.3),
    dplyr,
    glue,
    ggplot2,
    MASS,
    posterior,
    rlang,
    rstan (>= 2.26.11),
    stats,
    tidyr,
    utils
Suggests: 
    covr,
    knitr,
    plm,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Encoding: UTF-8
Roxygen: list(markdown = TRUE, roclets = c ("namespace", "rd",
    "srr::srr_stats_roclet"))
RoxygenNote: 7.2.1
LazyData: true
LazyDataCompression: xz


```

## Pre-submission Inquiry

- [x] A pre-submission inquiry has been approved in [issue #552](https://github.com/ropensci/software-review/issues/552) 

## General Information

-   Who is the target audience and what are scientific applications of this package?

The package is mainly intended for applied researchers working with complex panel data.
Panel data is common in many scientific fields, especially in sociology and econometrics. For example, analysing individual-level life-course data is valuable for assessing the effects of policy reforms and other interventions.

-   Paste your responses to our [*General Standard* **G1.1** here](https://stats-devguide.ropensci.org/standards.html#general-standards), describing whether your software is:

The `dynamite` R package provides easy-to-use interface for Bayesian inference of complex panel (time series) data comprising of multiple measurements per multiple individuals measured in time. The main features distinguishing the package and the underlying methodology from many other approaches are:

* Support for both time-invariant and time-varying effects modeled via B-splines.
* Joint modeling of multiple measurements per individual (multiple channels) based directly on the assumed data generating process.
* Support for non-Gaussian observations: Currently Gaussian, Categorical, Poisson, Bernoulli, Binomial, Negative Binomial, Gamma, Exponential, and Beta distributions are available and these can be mixed arbitrarily in multichannel models.
* Allows evaluating realistic long-term counterfactual predictions which take into account the dynamic structure of the model by posterior predictive distribution simulation.
* Transparent quantification of parameter and predictive uncertainty due to a fully Bayesian approach.
* User-friendly and efficient R interface with state-of-the-art estimation via [Stan](https://mc-stan.org/users/interfaces/rstan).

There are several R packages in CRAN focusing on panel data analysis including but not limited to:

* [`plm`](https://cran.r-project.org/web/packages/plm/index.html) for linear panel data models.
* [`fixest`](https://cran.r-project.org/web/packages/fixest/index.html) for fixed effects and different distributions of response variables (based on `stats::family`). 
* [`panelr`](https://cran.r-project.org/web/packages/panelr/index.html) for "within-between" models which combine fixed effect and random effect models.
* [`lavaan`](https://cran.r-project.org/web/packages/lavaan/index.html) for general structural equation modelling, and thus can be used to estimate various panel data models such as cross-lagged panel models with fixed or random intercepts.

However, to the best of our knowledge, there are no other R packages (or software in general) that support all features of `dynamite` simultaneously. Thus *The first implementation of a novel algorithm* seems most applicable.

-   (If applicable) Does your package comply with our [guidance around *Ethics, Data Privacy and Human Subjects Research*](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable.

## Badging

-    What grade of badge are you aiming for? ([bronze, silver, gold](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-badges))

Gold.

-    If aiming for silver or gold, describe which of the [four aspects listed in the *Guide for Authors* chapter](https://stats-devguide.ropensci.org/pkgdev.html#pkgdev-silver) the package fulfils (at least one aspect for silver; three for gold)

We designed `dynamite` from the ground up with the standards in mind and thus we think the package fulfills all four aspects. We have been able to comply with 129 standards with only 42 N/A standards across the "Bayesian and Monte Carlo" and "Regression and Supervised Learning" categories. The package is very general and capable of supporting a wide range of data and model structures as demonstrated by the examples and the package tests. In our opinion, the internal structure of the package is also well motivated and compartmentalized. We have also tried to carefully select the package dependencies and keep them to a minimum.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or have another maintainer identified.
- [x] I/we have read the [*Statistical Software Peer Review* Guide for Authors](https://stats-devguide.ropensci.org/pkgdev.html).
- [ ] I/we have run [`autotest`](https://github.com/ropensci-review-tools/autotest) checks on the package, and ensured no tests fail.
  `autotest` reports failures for the following tests:
  ```r
      type       test_name        fn_name          parameter parameter_type   operation                      content         
     <chr>      <chr>            <chr>            <chr>     <chr>            <chr>                          <chr>            
   1 diagnostic single_char_case get_code         time      single character upper-case character parameter is case dependent
   2 diagnostic single_char_case get_code         group     single character upper-case character parameter is case dependent
   3 diagnostic single_char_case get_data         time      single character upper-case character parameter is case dependent
   4 diagnostic single_char_case get_data         group     single character upper-case character parameter is case dependent
   5 diagnostic single_char_case get_priors       time      single character upper-case character parameter is case dependent
   6 diagnostic single_char_case get_priors       group     single character upper-case character parameter is case dependent
   7 message    NA               mcmc_diagnostics NA        NA               normal function call           0 of 400 iterati…
   8 message    NA               mcmc_diagnostics NA        NA               normal function call           0 of 400 iterati…
   9 message    NA               mcmc_diagnostics NA        NA               normal function call           E-BFMI indicated…
  10 message    NA               mcmc_diagnostics NA        NA               NA                             0 of 400 iterati…
  11 message    NA               mcmc_diagnostics NA        NA               NA                             0 of 400 iterati…
  12 message    NA               mcmc_diagnostics NA        NA               NA                             E-BFMI indicated…
  ```
  The first six of these report that the `time` and `group` parameters of several functions are case dependent. This is by design, as both of these parameters correspond to column names of the input data. While not entirely sure, we believe the remaining failures occur because the function `mcmc_diagnostic` produces messages while not being a print or a summary method, but this is also by design as the function outputs diagnostic messages related to the MCMC runs. The output of `autotest` is not very clear on this matter, as all columns are just filled with `NA` values.
- [x] The [`srr_stats_pre_submit()` function](https://ropensci-review-tools.github.io/srr/reference/srr_stats_pre_submit.html) confirms this package may be submitted.
- [x] The [`pkgcheck()` function](https://docs.ropensci.org/pkgcheck/reference/pkgcheck.html) confirms this package may be submitted - alternatively, please explain reasons for any checks which your package is unable to pass.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://devguide.ropensci.org/building.html#readme).

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by mpadge** [comment] 2022-08-23 13:09
@ropensci-review-bot check package

**Comment by mpadge** [comment] 2022-08-23 13:15
@santikka Thank you for your help debugging and improving our check system. Sorry the checks took so long to appear here.

@adamhsparks Please ignore the failing checks. The duplicated names check will soon be downgraded from a fail to a note. The other check is brand new. @santikka Feel free to modify your repo to describe return values, but do so at your own leisure, and consider all checks as passing for now. Thanks for all the help!

**Comment by santikka** [comment] 2022-08-23 14:02
@mpadge No worries, glad to help! I will add the missing return values soon.

**Comment by santikka** [comment] 2022-08-24 07:20
@mpadge About the return values: the system does not seem to recognize function aliases. For example in the above, `obs` and `aux` are aliases of `dynamiteformula` and thus have the same return value implicitly. If I explicitly add the return tag to these aliases as well, the resulting documentation looks rather silly with regards to the output value:
```
Value
A dynamiteformula object.

A dynamiteformula object.

A dynamiteformula object.
```

**Comment by adamhsparks** [comment] 2022-08-25 13:30
@ropensci-review-bot assign @noamross as editor

**Comment by noamross** [comment] 2022-09-06 22:56
@ropensci-review-bot seeking reviewers

**Comment by noamross** [comment] 2022-09-06 22:57
@ropensci-review-bot assign @nicholasjclark as reviewer

**Comment by nicholasjclark** [comment] 2022-09-21 00:44
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   **Briefly describe any working relationship you have (had) with the package authors.**
-   ☒ As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

#### Documentation

The package includes all the following forms of documentation:

-   ☒ **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
-   ☒ **Installation instructions:** for the development version of package and any non-standard dependencies in README
-   ☒ **Vignette(s):** demonstrating major functionality that runs successfully locally
-   ☒ **Function Documentation:** for all exported functions
-   ☒ **Examples:** (that run successfully locally) for all exported functions
-   ☒ **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

-   ☒ **Installation:** Installation succeeds as documented.
-   ☒ **Functionality:** Any functional claims of the software been confirmed.
-   ☒ **Performance:** Any performance claims of the software been confirmed.
-   ☐ **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
-   ☒ **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 5

-   ☒ Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer (“rev” role) in the package DESCRIPTION file.

------------------------------------------------------------------------

### Review Comments

This is a very nicely-documented package that provides a rich set of functions all tailored towards a single purpose or estimating complex panel models and interrogating resulting models. The authors make good arguments as to why the package is needed, how it extends existing software and who the target audience is. I have not used these models personally so I found it a little difficult to understand how I would go about implementing them for my own purposes. On this note I do feel that the planned accompanying papers will be essential for introducing unfamiliar users to the package. Some extra detail in the vignette and readme could help to provide a bit more context about what the parameters mean and how the models can be interpreted, but overall this does not detract from the soundness of the package itself.

The only issue I find in general testing is that I receive a single failure during unit testing:

Error (test-recovery.R:22:3): parameters for the linear regression are recovered as with lm Error in `do.call("dynamite", list(dformula = x, data = data, group = group,      time = time, debug = list(no_compile = TRUE), ...))`: argument “group” is missing, with no default.

All examples pass on my machine, and they are appropriate for demonstrating the functionality of the package. I do however have a few general notes:

There appears to be a typo in the vignette on line 383 due to a missing closing parenthesis (change `mutate(invest = inv, firm = factor(firm)` to `mutate(invest = inv, firm = factor(firm))`)

On line 398 in the vignette I receive the following error: `unused argument (random_intercept = TRUE)`

On line 514 in the vignette, the text states that the output is a two-component `list`, but in my run I get a `dataframe`

Some guidelines for contributing could be listed explicitly if the authors would welcome community contributions

The package has quite a few dependencies that make installation a lengthy process. Could any of this be streamlined? Also, the reliance on the newest version of `R` could be a deterrent for some users. If `dplyr` and `magrittr` are used then why is the native pipe necessary?

I see no reason why the authors shouldn’t allow for `cmdstanr` (in addition to `rstan`) to be a backend option for sampling. This would allow a broader range of users to work with the package, as `Cmdstan` is usually ahead of `rstan` in terms of features (not to mention much better performance on most systems)

The options for updating priors and for generating `Stan` code and data objects are incredibly useful and will allow users to modify the files to suit their analyses. However some additional annotations of the `Stan` code would be helpful to give users better familiarity with the programs, as would a worked example to illustrate how the code could be modified and run outside of `dynamite`. I also find annotations to be a bit lacking throughout most of the functions. Again this doesn’t harm performance or tidiness of the package but it makes it challenging for users (such as myself) who might want to adapt some of the code for their own workflows and packages. For example, what is the purpose of each chain in the long pipe used in the `as_draws_df.dynamitefit` function? A few simple annotations would clarify what calculations / manipulations are taking place

It is not clear how users can simulate from the prior to help inform model development. This would be a useful addition to vignettes / examples as it is an essential component of a modern Bayesian workflow

`mcmc_diagnostics` function is very useful for a quick overview of estimator performance

Very impressive and thorough set of unit tests

Each function appears to have a standalone usage that is well documented

Links to the code used for creation of example datasets are excellent tools for demonstrating how users can implement simulations in their own workflows

**Comment by noamross** [comment] 2022-09-21 14:52
Thank you for your review, @nicholasjclark!  I note you used the non-statistical reviewer template.  Would you be able to use the statistical one at https://stats-devguide.ropensci.org/pkgreview.html#pkgrev-template?  My apologies, it looks like the one linked above is dead so you probably searched out and found that one.

I am still seeking a second reviewer, @santikka. I suggest limiting updates until you have inputs from both.

**Comment by santikka** [comment] 2022-09-28 09:45
Hi @nicholasjclark,

Thank your for the comprehensive review. We agree that the documentation in its current form is still lacking, and as we move toward writing the relevant papers, the situation will gradually improve as a consequence.

We have corrected the error in the unit testing. We have also corrected the errors and typos in the vignette.

While the native pipe is not strictly necessary, we still prefer it over the `magrittr` pipe because it is future-proof in a sense and is already widely adopted such as in RStudio and in the newest edition of the popular Advanced R book. The native pipe also has zero overhead in performance.

We have managed to drop the dependency on the development versions of `rstan` and `StanHeaders`. This only affects the case where the model contains categorical responses, for which the sampling will be much slower with older versions of these packages. A warning is now issued in such instances.

We have added the option to use `cmdstanr` as a backend for sampling which can be used with argument `backend = "cmdstanr"` in the `dynamite` call.

We have added helpful annotations to the more complicated section of the generated `Stan` code as well as in other parts of the package code itself. Some larger functions such as `dynamite` itself have been broken down to smaller simpler functions.

We have added an example on how to simulate from the prior predictive distribution to the documentation pages of `predict`. Note that this is not particularly useful for the complex models of `dynamite` because as with other flexible time-series models which do not enforce stationarity, the simulated series tend to vary too much and can "explode" with large number of time points.

**Comment by nicholasjclark** [comment] 2022-09-28 23:53
> Thank you for your review, @nicholasjclark! I note you used the non-statistical reviewer template. Would you be able to use the statistical one at https://stats-devguide.ropensci.org/pkgreview.html#pkgrev-template? My apologies, it looks like the one linked above is dead so you probably searched out and found that one.
> 
> I am still seeking a second reviewer, @santikka. I suggest limiting updates until you have inputs from both.

Hi @noamross. Sorry I didn't see your reply until now, would you still like me to use the statistical template now that @santikka has responded to the original review?

**Comment by noamross** [comment] 2022-09-29 11:04
@nicholasjclark Yes, please do. Thanks!

**Comment by santikka** [comment] 2022-11-21 13:45
Hi @noamross! Would it be possible to get a status update regarding the review process? It has now been over one month since the second review deadline.

**Comment by LucyMcGowan** [comment] 2022-11-21 13:46
Im so sorry I’m so behind! Hoping to wrap this up soon

**Comment by LucyMcGowan** [comment] 2022-12-06 16:11
## Package Review

- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

---

### Compliance with Standards

- [x] This package complies with a sufficient number of standards for a gold badge
- [x] This grade of badge is the same as what the authors wanted to achieve

The following standards currently deemed non-applicable (through tags of `@srrstatsNA`) could potentially be applied to future versions of this software: (Please specify)

Please also comment on any standards which you consider either particularly well, or insufficiently, documented.

For packages aiming for silver or gold badges:

- [ ] This package extends beyond minimal compliance with standards in the following ways: (please describe)

---

### General Review

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING
- [x] The documentation is sufficient to enable general use of the package beyond one specific use case

#### Algorithms

The algorithms are encoded well. The language is appropriate, and all tests passed on my machine.

#### Testing

This package has extensive testing and all tests passed on my machine.

The examples and vignette, however, are not currently compiling, for example, when I run the first example of the `dynamite` function I get the following error:

``` r
library(dynamite)
fit <- dynamite(
       dformula = obs(y ~ -1 + varying(~x), family = "gaussian") +
         lags(type = "varying") +
         splines(df = 20), gaussian_example, "id", "time",
       chains = 1,
       refresh = 0
     )
#> Error in `[.data.table`(data, idx, cl, env = list(cl = cl)): unused argument (env = list(cl = cl))
```

<sup>Created on 2022-12-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

#### Visualisation (where appropriate)

- Do visualisations aid the primary purposes of statistical interpretation of results?
I am able to see the visualization in the README, they look good. Unfortunately, I am not able to compile the vignette due to the error above.

- Are there any aspects of visualisations which could risk statistical misinterpretation?
No

#### Package Design

- Is the package well designed for its intended purpose?
Yes
- In relation to **External Design:** Do exported functions and the relationships between them enable general usage of the package? 
Yes
- In relation to **External Design:** Do exported functions best serve inter-operability with other packages?
Yes
- In relation to **Internal Design:** Are algorithms implemented appropriately in terms of aspects such as efficiency, flexibility, generality, and accuracy? 
Yes
- In relation to **Internal Design:** Could ranges of admissible input structures, or form(s) of output structures, be expanded to enhance inter-operability with other packages?
The output seems to work well with common functions, like those from the tidyverse.

---

- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

Estimated hours spent reviewing: 2.5

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

**Comment by santikka** [comment] 2022-12-07 08:33
@LucyMcGowan Thank you for the review!

Regarding the error, `dynamite` currently requires the development version of the `data.table` package (which can be installed via `data.table::update.dev.pkg()`). There is some confusion about the version numbers, since the required version `1.14.3` of `data.table` is already on CRAN, but the particular feature used by dynamite was not included in the CRAN release: https://github.com/Rdatatable/data.table/issues/5538 we will update the readme accordingly to avoid confusion.

**Comment by nicholasjclark** [comment] 2022-12-08 00:40
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   Briefly describe any working relationship you may have (had) with the package authors (or otherwise remove this statement)

-   ☒ As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (If you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

------------------------------------------------------------------------

### Compliance with Standards

-   ☒ This package complies with a sufficient number of standards for a (bronze/silver/gold) badge
-   ☒ This grade of badge is the same as what the authors wanted to achieve

The following standards currently deemed non-applicable (through tags of `@srrstatsNA`) could potentially be applied to future versions of this software: (Please specify)

Please also comment on any standards which you consider either particularly well, or insufficiently, documented.

For packages aiming for silver or gold badges:

-   ☒ This package extends beyond minimal compliance with standards in the following ways: (please describe)

The authors have been able to comply with 129 standards with only 42 N/A standards across the “Bayesian and Monte Carlo” and “Regression and Supervised Learning” categories and the function design is very well compartmentalised in my view

------------------------------------------------------------------------

### General Review

#### Documentation

The package includes all the following forms of documentation:

-   ☒ **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
-   ☒ **Installation instructions:** for the development version of package and any non-standard dependencies in README
-   ☒ **Community guidelines** including contribution guidelines in the README or CONTRIBUTING
-   ☒ The documentation is sufficient to enable general use of the package beyond one specific use case

The following sections of this template include questions intended to be used as guides to provide general, descriptive responses. Please remove this, and any subsequent lines that are not relevant or necessary for your final review.

#### Algorithms

-   How well are algorithms encoded?
-   Is the choice of computer language appropriate for that algorithm, and/or envisioned use of package?
-   Are aspects of algorithmic scaling sufficiently documented and tested?
-   Are there any aspects of algorithmic implementation which could be improved?

As the maintainers have now allowed for `cmdstanr` to be used as a backend, any efficiency updates can generally be automatically incorporated as long as users keep their `Cmdstan` and `cmdstanr` packages up to date. Perhaps some instructions to the users in the `Readme` can help to clarify this

#### Testing

-   Regardless of actual coverage of tests, are there any fundamental software operations which are not sufficiently expressed in tests?
-   Is there a need for extended tests, or if extended tests exists, have they been implemented in an appropriate way, and are they appropriately documented?

Very impressive and thorough set of unit tests

#### Visualisation (where appropriate)

-   Do visualisations aid the primary purposes of statistical interpretation of results?
-   Are there any aspects of visualisations which could risk statistical misinterpretation?

Visualisations make use of `ggplot` objects, which are very familiar to most potential users. There is no risk of misinterpretation in my view

#### Package Design

-   Is the package well designed for its intended purpose?
-   In relation to **External Design:** Do exported functions and the relationships between them enable general usage of the package?
-   In relation to **External Design:** Do exported functions best serve inter-operability with other packages?
-   In relation to **Internal Design:** Are algorithms implemented appropriately in terms of aspects such as efficiency, flexibility, generality, and accuracy?
-   In relation to **Internal Design:** Could ranges of admissible input structures, or form(s) of output structures, be expanded to enhance inter-operability with other packages?

Function designs and levels of documentation are excellent and the returned structures will integrate very well with popular post-processing packages designed to work with `stanfit` objects. The algorithms make use of `stan`, which is the most efficient implementation of MCMC in the `R` programming environment. I see no issues with the way the package is designed

------------------------------------------------------------------------

-   ☒ **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

Estimated hours spent reviewing: 5

-   ☒ Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer (“rev” role) in the package DESCRIPTION file.

**Comment by LucyMcGowan** [comment] 2022-12-08 18:46
Thank you! I updated to the dev version of `data.table` and was able to compile everything. I did try to follow the instructions in the README by running `data.table::update.dev.pkg()` but got the following message: `Error: 'update.dev.pkg' is not an exported object from 'namespace:data.table'`. I have updated my review above. Thank you!

**Comment by santikka** [comment] 2022-12-08 19:41
@LucyMcGowan It seems that at some point the development version installation function of `data.table` was renamed into `update_dev_pkg` instead, apologies! The README has been corrected accordingly.

**Comment by santikka** [comment] 2022-12-09 08:31
Based on the reviews, we have taken some additional steps to make the package installation more straightforward and the requirements less strict:

- The package no longer depends on `dplyr` or `tidyr`, and the internal package code that previously used these packages is now written entirely using `data.table` instead. `dplyr` and `tidyr` are only used in examples and tests, and are now included as 'Suggests' instead.
- The package no longer depends on R version 4.1.0. The native pipe `|>` is no longer used internally, and is used only in the examples conditionally on the installed R version of the user.
- The categorical distribution is now also supported for older `rstan` and `cmdstanr` versions.

**Comment by noamross** [comment] 2022-12-09 19:43
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/554#issuecomment-1341808955  time 5

**Comment by noamross** [comment] 2022-12-09 19:44
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/554#issuecomment-1339614792 time 4

**Comment by noamross** [comment] 2022-12-09 19:56
Thank you all for bearing with us and following up! @LucyMcGowan and @nicholasjclark, you seem to have indicated in your follow-ups, but to be unambiguous, do the updates resolve any outstanding comments for acceptance at gold level?

**Comment by LucyMcGowan** [comment] 2022-12-09 20:01
Yes, I approve acceptance at the gold level. Thanks @noamross!

**Comment by nicholasjclark** [comment] 2022-12-13 03:38
> Thank you all for bearing with us and following up! @LucyMcGowan and @nicholasjclark, you seem to have indicated in your follow-ups, but to be unambiguous, do the updates resolve any outstanding issues for acceptance at gold level?

Yes I approve acceptance as well. Thanks very much

**Comment by noamross** [comment] 2022-12-13 22:39
@ropensci-review-bot approve dynamite

**Closed** 2022-12-13 22:39 UTC
Labels: 6/approved, stats, 6/approved-gold-v0.2

**Comment by santikka** [comment] 2022-12-14 05:55
@ropensci-review-bot finalize transfer of dynamite
