### ISSUE TITLE
submission: CRAN pacakge icd

### ISSUE THREAD

**Issue by jackwasey** [ropensci/software-review#236] opened 2018-07-12 14:48 UTC
### Summary

-   What does this package do? (explain in 50 words or less):

Classifies medical diagnostic codes into disease comorbidity groups, calculates risk scores, and converts between types of ICD code, and decodes them to plain language.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: icd
Title: Tools for Working with ICD-9 and ICD-10 Codes, and
    Finding Comorbidities
Version: 3.2.1
Authors@R: 
    c(person(given = "Jack O.",
             family = "Wasey",
             role = c("aut", "cre", "cph"),
             email = "jack@jackwasey.com",
             comment = c(ORCID = "0000-0003-3738-4637")),
      person(given = "William",
             family = "Murphy",
             role = "ctb",
             email = "WMurphy@eatright.org",
             comment = "Van Walraven scores"),
      person(given = "Anobel",
             family = "Odisho",
             role = "ctb",
             email = "anobel.odisho@ucsf.edu",
             comment = "Hierarchical Condition Codes"),
      person(given = "Vitaly",
             family = "Druker",
             role = "ctb",
             email = "vdruker@gmail.com",
             comment = "AHRQ CCS"),
      person(given = "Ed",
             family = "Lee",
             role = "ctb",
             comment = "explain codes in table format"),
      person(given = "Kevin",
             family = "Ushey",
             role = "ctb",
             comment = "Code adapted for fast factor generation"),
      person(given = "R Core Team",
             role = c("ctb", "cph"),
             comment = "m4 macro for OpenMP detection in configure"))
Maintainer: Jack O. Wasey <jack@jackwasey.com>
Description: Calculate comorbidities, Charlson scores, perform
    fast and accurate validation, conversion, manipulation, filtering and
    comparison of ICD-9 and ICD-10 codes. This package enables a work flow
    from raw lists of ICD codes in hospital databases to comorbidities.
    ICD-9 and ICD-10 comorbidity mappings from Quan (Deyo and Elixhauser
    versions), Elixhauser and AHRQ included.  Common ambiguities and code
    formats are handled.
License: GPL-3
URL: https://jackwasey.github.io/icd/
BugReports: https://github.com/jackwasey/icd/issues
Depends:
    R (>= 3.4),
    icd.data
Imports:
    checkmate (>= 1.7.0),
    magrittr,
    stats,
    Rcpp (>= 0.12.3),
    utils
Suggests:
    knitr,
    roxygen2 (>= 5.0.0),
    rmarkdown,
    rticles,
    testthat (>= 0.11.1),
    tinytex,
    xml2
LinkingTo:
    Rcpp (>= 0.12.3),
    RcppEigen,
    testthat
VignetteBuilder: 
    knitr
ByteCompile: true
Classification/ACM-2012: Social and professional topics~Medical
    records, Applied computing~Health care information systems, Applied
    computing~Health informatics, Applied computing~Bioinformatics
Copyright: See file (inst/)COPYRIGHTS
LazyData: true
LazyDataCompression: xz
RoxygenNote: 6.0.1

```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/jackwasey/icd

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data munging: although data extraction is built in, the core functionality is the comorbidity calculation which is data munging.

-   Who is the target audience and what are scientific applications of this package?  
health and medical science researchers, public health, epidemiology, global health

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

No other package manipulates ICD codes. There are some overlapping comorbidity calculation packages. 'comorbidity' is a new package. It is much slower than icd to produce the same results (see JSS vignette in 'icd'), and is more demanding of the user in setting up data in the format required (e.g. 'icd' guesses field names, and structure of ICD codes, making conversions automatically when possible). More problematically, 'comorbidity' is very generous in accepting and classifying invalid ICD codes into comorbidities. This has been thought through carefully over years in 'icd' and with feedback from the many users. The JSS article submission vignette touches on the decisions made around this.

'medicalrisk' has similar deficits to 'comorbidity'. 'pccc' is specifically focussed on comorbities of one type (pediatric complex chronic conditions), and does these also much slower than 'icd' (which also offers PCCC calculations), despite using Rcpp and parallelization. 

'icd' has a carefully thought out algorithm to do this quickly which is unique in the R package ecosystem. In addition, 'icd' calculates comorbidities of more kinds, (CSS and HCC, from contributed code). 'icd' uses S3 classes to be extensible to different national and international variations of the ICD coding scheme from the WHO.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

NA

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with.  (NA)
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  (it already is)
- [x] NO - a JSS article has been submitted] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)?
- [x] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? No.
### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

functions are named as follows:

 -  icd9_... for functions which operate on ICD-9 codes
 - icd10_... for functions which operate on ICD-10 codes
 - functions which operate on either (determined based on input) are not prefixed. This decision was taken because of Hadley Wickham's recommendation not to use library, but to write the external package namespace each time, so I expect users might prefer to use, e.g. `icd::comorbid_ahrq(my_patients)`. In any case, the names of functions do not overlap with any well known functions. Previously `explain()` was changed to `explain_code()` for this reason.

- If this is a resubmission following rejection, please explain the change in circumstances:
NA

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

### other

There is an accompanying package called 'icd.data' which contains the rarely changing, larger data sets required for 'icd' to function. It is also on CRAN and is very simple. Should I submit a separate onboarding issue for this pacakge? Thanks.

**Comment by jackwasey** [comment] 2018-07-12 22:45
Thanks for getting back so quickly.

1. I'm not 100% sure what you mean, but I can say that the scores are standardized and used very widely through medical research over many years. There are no novel calculations in the package, just accurate and validated implementations of the existing standards. These are all referenced in the documentation.
2. Yes, the vignette "Efficient ..." is submitted to JSS and under review.

**Comment by maelle** [comment] 2018-07-13 16:36
Thanks for your answers @jackwasey!

Your package seems in scope but it cannot be reviewed simultaneously at the two venues. It's up to you to have `icd` reviewed first at JSS or here. Note that our reviews might result in request for changes, even for the stuff reviewed/requested by JSS. With that in mind, do you want to put this submission on hold?

**Comment by maelle** [comment] 2018-07-15 14:49
Ok, thanks, good luck with the JSS submission!

If our reviews result in big changes, we have [some guidance about that](https://ropensci.github.io/dev_guide/evolution.html).

**Comment by maelle** [comment] 2018-07-30 15:52
@rcih Could you please ask your question in the repo of the package i.e. https://github.com/jackwasey/icd/issues ? Thank you.

**Comment by jackwasey** [comment] 2018-07-30 15:55
Yes, @rcih please head to https://github.com/jackwasey/icd/issues and give a reproducible example. Thanks!

**Comment by rcih** [comment] 2018-07-31 13:06
Okay, will do @jackwasey. Thanks!

**Comment by sckott** [comment] 2019-02-25 20:10
@jackwasey  be aware that our policies https://ropensci.github.io/dev_guide/policies.html#review-process state that this issue will be closed after one year from applying the holding label (jul 2019) and you'll need to resubmit if the issue is closed

**Comment by maelle** [comment] 2019-08-14 05:56
@jackwasey any update?  Otherwise as per our policies mentioned above by @sckott, the issue will be closed because the submission has been on hold for more than one year.

**Comment by maelle** [comment] 2019-11-04 07:18
It's been more than one year, so closing this.

**Closed by maelle** 2019-11-04 07:18 UTC
Labels: holding, package
