### ISSUE TITLE
Submission of naijR 0.6.1 for review under the rOpenSci Champions Program

### ISSUE THREAD

**Issue by BroVic** [ropensci/software-review#600] opened 2023-08-13 17:05 UTC
**Date accepted:** 2023-12-02

Submitting Author Name: Victor Ordu
Submitting Author Github Handle: @BroVic

Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/BroVic/naijR

Version submitted: 0.6.1

Submission type: Standard

Editor: @emilyriederer

Reviewers: @mcsiple, @cagrigokcek

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: naijR
Type: Package
Title: Operations to Ease Data Analyses Specific to Nigeria
Version: 0.6.1
Depends: R (>= 3.6)
Imports:
    RColorBrewer (>= 1.1.2),
    cli (>= 3.6.0),
    lifecycle (>= 0.2.0),
    grDevices,
    graphics,
    mapdata (>= 2.3.0),
    maps (>= 3.3.0),
    rlang (>= 0.4.0),
    sf (>= 1.0.13),
    stats,
    stringi (>= 1.7.6),
    utils
Suggests: 
    ISOcodes,
    covr,
    here,
    knitr,
    purrr,
    readxl,
    rmarkdown,
    testthat (>= 3.0.0),
    usethis
Authors@R: person("Victor", "Ordu", 
              email = "victorordu@outlook.com",
              role = c("aut", "cre"),
              comment = c(ORCID = "0000-0003-3716-0668"))
Description: A set of convenience functions as well as geographical/political
  data about Nigeria, aimed at simplifying work with data and information that
  are specific to the country.
License: GPL-3
LazyData: TRUE
Encoding: UTF-8
RoxygenNote: 7.2.3
VignetteBuilder: knitr
RdMacros: lifecycle
URL: https://brovic.github.io/naijR/
BugReports: https://github.com/BroVic/naijR/issues
Config/testthat/edition: 3
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
naijR is an R package that contains a suite of functions that make it easier to deal with data and datasets about the country Nigeria and its constituent parts.

-   Who is the target audience and what are scientific applications of this package?
Anyone needing Nigerian geospatial data.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
Not to my knowledge.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Yes

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by BroVic** [comment] 2023-08-17 12:24
@ropensci-review-bot check package

**Comment by BroVic** [comment] 2023-08-18 17:52
@ropensci-review-bot check package

**Comment by noamross** [comment] 2023-08-22 15:55
@ropensci-review-bot assign @emilyriederer as editor

**Comment by emilyriederer** [comment] 2023-08-25 22:45
### Editor checks:

- [x] **Documentation**: The package has sufficient documentation available online (README, pkgdown docs) to allow for an assessment of functionality and scope without installing the package. In particular,
    - [x] Is the case for the package well made?
    - [x] Is the reference index page clear (grouped by topic if necessary)? **References page could be further organized with grouping (e.g. `fix` vs `is` functions), but given reasonable number of functions it is still clear**
    - [x] Are vignettes readable, sufficiently detailed and not just perfunctory?
- [ ] **Fit**: The package meets criteria for [fit](https://devguide.ropensci.org/policies.html#package-categories) and [overlap](https://devguide.ropensci.org/policies.html#overlap).
- [x] **Installation instructions:** Are installation instructions clear enough for human users?
- [x] **Tests**: If the package has some interactivity / HTTP / plot production etc. are the tests using [state-of-the-art tooling](https://devguide.ropensci.org/building.html#testing)? **NA**
- [ ] **Contributing information**: Is the documentation for contribution clear enough e.g. tokens for tests, playgrounds? **`CONTRIBUTION.md` file exists. It is not extensive, but given that the package does not require a complicated dev environment it is likely fine. However, information on which branch to clo**
- [x] **License:** The package has a CRAN or OSI accepted license.
- [x] **Project management**: Are the issue and PR trackers in a good shape, e.g. are there outstanding bugs, is it clear when feature requests are meant to be tackled? **Overall issues / PRs are clean. The only thing I notice is a large number of outstanding branches which are likely "stale" from past PRs. Considering deleting these if no longer needed.**
---

#### Editor comments

This package is in good shape and seems like it could be a powerful accelerant to a data science workflow. Before preceding with the review, I just notice a few changes to be made:

- Regarding Fit, the package is categorized as Geospatial. However, while the package works with location *names* it does not work with geospatial *data types*. Would "data munging" be a more appropriate category since this supports data cleaning operations?

Additionally, the following dimensions could be improved. However, these are not critical to move forward:

- More organization could be added to the References pages (by modifying the pkgdown yaml) to group like-functions together. However, I think it's sufficiently easy to navigate this page as-is. 
- More opinionated content could be added to the `CONTRIBUTING.md` file if the author wants to share standards for what he wishes to see in a contribution, if he prefers an issue submitted to discuss before receiving a PR, etc.
- Stale branches could be deleted to clean up the repo

---

**Comment by emilyriederer** [comment] 2023-08-25 22:47
Hi @BroVic ! It's great to meet you and I'm looking forward to working as your editor on this package. I left some comments above. I think we are close to looking for reviewers, but I'd love to discuss the "Fit" question with you first. Could you please review our [categories](https://devguide.ropensci.org/policies.html#package-categories) and let me know if you think this package fits the "Data munging" category more than "geospatial"?

**Comment by BroVic** [comment] 2023-08-26 05:52
Hello @emilyriederer, indeed the original intent for the package was not to draw maps but help with data validation and/or transformation. The mapping was really a child of necessity due to the absence of elements for drawing subnational maps in existing packages. Future versions will delve into ward level maps, but the focus is to provide objects that can be consumed by actual geospatial packages. So I agree&mdash;we could recategorize it as you've suggested.

**Comment by emilyriederer** [comment] 2023-08-26 11:00
Hi @BroVic - thanks for the reply. I think it makes sense to chose the category the best represents the current scope of the package. If you're aligned, please change the category in your initial post at the top.

After that, I'm comfortable moving to identify reviewers. However, I'd encourage you to check out a few of the other notes in my "Editor comments" above in the meantime.

Thanks!

**Comment by emilyriederer** [comment] 2023-08-29 23:17
@ropensci-review-bot seeking reviewers

**Comment by BroVic** [comment] 2023-08-31 06:25
Hello @emilyriederer 

I've made some changes to address your comments. Thank you very much!

**Comment by emilyriederer** [comment] 2023-09-02 23:03
@ropensci-review-bot add @mcsiple to reviewers

**Comment by emilyriederer** [comment] 2023-09-02 23:05
Hi @BroVic - I'm thrilled to introduce @mcsiple as the first reviewer for your package! Her expertise is in both text and spatial data so she seemed like a great fit for this package. I should have an update on the second reviewer soon.

**Comment by BroVic** [comment] 2023-09-03 06:20
Thank you @emilyriederer. I really appreciate your efforts and I can't wait to learn from you guys. Cheers!

**Comment by emilyriederer** [comment] 2023-09-03 21:46
@ropensci-review-bot add @cagrigokcek to reviewers

**Comment by emilyriederer** [comment] 2023-09-03 21:50
Hi @BroVic ! I'm delighted to introduce the @cagrigokcek as the second reviewer. His domain expertise is in political science, so I'm sure that will help him empathize with potential users of this package. Earlier this summer, he was featured in [this rOpenSci blog post](https://ropensci.org/blog/2023/06/19/ropensci-champions-program-teams-meet-alican-cagri-gokcek-and-elio-campitelli/)

**Comment by BroVic** [comment] 2023-09-04 09:59
Hello @emilyriederer, noted with thanks 👍🏽

**Comment by mcsiple** [comment] 2023-09-22 22:25
## `naijR` Package Review
Good work on this package @BroVic et al. I used the rOpenSci review template to set up my checks. My limited comments/suggestions can be found at the bottom of this review. Please let me know if you have any questions about anything I wrote. 

- **Briefly describe any working relationship you have (had) with the package authors.**
- [X] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s):** demonstrating major functionality that runs successfully locally
- *The vignettes are easy to use and both work. I had to use `devtools::build_vignettes()` after installing directly from github source. The nigeria-maps vignette had a build error because one or two calls to `map_ng()` use `fill` as an argument when I think it should be `exclude_fill`. Suggest adding a `build_vignettes` argument to install instructions in README.md .(`remotes::install_github("BroVic/naijR",build_vignettes = TRUE)`)*
- [ ] **Function Documentation:** for all 
`as_lga()` / `is_lga()` -- works and examples run great.
`fix_region()` - I like the interactive option for fixing region names; this is a smart addition to the package.
`map_ng()` - In documentation for map_ng, "sw" is not recognized as a state (i.e., when you run `map_ng(states("sw"))` you get a warning "One or more items is not a State"). I am a little unclear about the CRS for the points in the "Mapping of point data" vignette. I assume that many users will have lats and lons and will want to plot those over the map, or use the spatial data to assign points to states. If there is a way to do this with `naijR`, can you demonstrate in the nigera-maps vignette? Or otherwise provide an example where the `sf` object generated from `map_ng()` is used. 

- [X] **Examples:** (that run successfully locally) for all exported functions
- [X] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [X] **Installation:** Installation succeeds as documented. 
*But see note about vignettes above*
- [X] **Functionality:** Any functional claims of the software been confirmed.
- [X] **Performance:** Any performance claims of the software been confirmed.
- [X] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine. 
Test coverage is good (I used `covr::package_coverage()`)
- [X] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing:

- [X] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments
Great work putting together the package so comprehensively. It made it easier to review and will be easier for users, too. I have just a couple of comments.

- Installs with devtools and from source worked great. See suggestions above about adding a vignette argument. 
- You might want to change the dependency for maptools here to avoid the warning messages that users will likely get about maptools being discontinued in favor of sf/terra. Suppressing warnings about this is in your News doc so I bet you are already thinking about doing this.
-`map()` and `regions()` produced warnings when I ran `goodpractice::gp()` about unit test coverage, but I think 97% coverage is pretty good so I will leave it to the editor to decide if additional coverage is really necessarily on those. 
- `{goodpractice}` also suggests avoiding `sapply()` (used in admin.R, helpers.R and utils.R). 
- An optional thing that would be nice would be some additional detail about how the name disambiguations are produced. For example, when `fix_region()` is automatic, what is the underlying method used to get the disambiguation? This may help others who are working on similar data packages, and help them troubleshoot when misspellings are too 'far gone' to produce an automatic correction.
- Minor note - if there is a source for the geographical data or the "official" anglicized spelling of the LGA or state names, that might be worth adding.

**Comment by emilyriederer** [comment] 2023-09-28 09:38
Thanks for the review, @mcsiple ! I really appreciate the thorough suggestions here. 

@cagrigokcek , do you have an update from your side of when you will have your review completed?

**Comment by cagrigokcek** [comment] 2023-09-28 20:42
Hi Emily,

Is it ok if I submit my review by the end of Sunday night? I know that I already demanded a few days extra. But, this will be the last and final request from me. Please let me know.

Best.

Cagri

**Comment by emilyriederer** [comment] 2023-09-29 09:43
Thanks for the update, @cagrigokcek ! Yes, that should work just fine. I
appreciate your taking the time to do a thorough review!

**Comment by cagrigokcek** [comment] 2023-10-02 00:53
Hello @Brovic,
I am very happy to give you feedback. As you know, this is my first chance of getting involved in a peer-review process. That said, please forgive me if I miss any crucial point in this review, and don't hesitate to forward me any type of accessibility-related questions. In this review, I majorly focused on your map_ng() function. My main goal was checking the level of accessibility of maps created by your package. Thus, I skipped some items in the check list due to the lack of enough knowledge to test them. Drawing insights from this review process, I also offer an extra bullet point under the heading of functionality to @emilyriederer on behalf of @rOpenSci. I added a new bullet point below, and left my feedback there. I hope that it will help @BroVic to make naijR more inclusive and accessible for everyone.:

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [X] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [ ] **Function Documentation:** for all exported functions
- [ ] **Examples:** (that run successfully locally) for all exported functions
- [ ] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.
- [ ] **Accessibility of package:**

I will recommend to benefit from BrailleR packages' functions for discovering maps in the package. the pertinant information about BrailleR in regards to making data visualization more accessible for the blind can be obtained via this vignette:
https://cran.r-project.org/web/packages/BrailleR/vignettes/ExploringGraphs.html
When I created two objects by map_ng(), I was not able to use BraileR's relevant commends for graphs. At this moment, I should also admit that I am not sure whether BrailleR's commands work for maps. I know that BrailleR works smoothly with ggplot2 and tidyverse in general. I am sharing my codes and the message received in R for @BroVic's consideration.

``` r
library(naijR)
library(BrailleR)
map1=map_ng("Nigeria")

Describe(map1)
#> No description of this type of object has been written at this time.
#> 
#> General Description:
#> none yet
#> 
#> R hints:
#> none yet

map2=map_ng()

Describe(map2) 
#> No description of this type of object has been written at this time.
#> 
#> General Description:
#> none yet
#> 
#> R hints:
#> none yet
```

Describe function, if it worked, could allow a screen reader user to understand basic features of the maps such as the state names displayed in the map, their geographic position in the map, the color of states, if any, in the map, and any other features considered fundamentally important by the author of the package. 
Here, I only demonstrated Describe() function. Other functions of BrailleR (e.g. VI()) can be integrated in naijR package to increase the inclusivity of naijR package.
Overall, as it is seen, a development task for naijR can be making naijR package compatible with BrailleR package's commands related to data visualization.  
 
Estimated hours spent reviewing:

- [X] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments
I am very excited to see what kind of changes can ebedone for improving the accessibility of maps in this package. Please don't hesitate to keep in touch with me anytime if you need me to test your new features.

**Comment by BroVic** [comment] 2023-10-02 06:05
Thank you, @mcsiple and @cagrigokcek  for your detailed reviews. I will proceed to incorporate your input and will revert when I'm done or if I run into any issues.

**Comment by emilyriederer** [comment] 2023-10-06 00:02
Thank you so much for the reviews @mcsiple and @cagrigokcek ! Could you please both share an estimated time spent reviewing? This is a metric we track internally and I need it so I can trigger the bot to formally "submit" the reviews

**Comment by mcsiple** [comment] 2023-10-06 02:25
Sorry about that! I missed it the first time. I just edited my comment in the thread above with the estimated hours spent reviewing.

**Comment by emilyriederer** [comment] 2023-10-06 09:30
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/600#issuecomment-1732091598 time 5

**Comment by emilyriederer** [comment] 2023-10-06 09:31
Thanks @mcsiple ! Not a problem at all -- I know there's a lot of information to fill out on those!

**Comment by cagrigokcek** [comment] 2023-10-06 22:07
Hi Emily,

I didn’t actually count my hours while reviewing the package. I spent few hours in two days to complete the review. I should say that I didn’t spend more than 5 hours in two days. 

Thanks.

Cagri

**Comment by emilyriederer** [comment] 2023-10-06 23:20
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/600#issuecomment-1742267778 time 5

**Comment by emilyriederer** [comment] 2023-10-15 00:37
Hi @BroVic ! I hope you are well. I thought I'd drop a line and see how you are feeling about any changes inspired by the review comments? It would be great if we can give our reviewers a heads-up on when to expect a final version to review for approval. Thanks!

**Comment by BroVic** [comment] 2023-10-15 17:07
Dear @emilyriederer I thought I would have finished applying the requested updates by now, but I had a little battle with malaria last weekend. I'm fine now and recuperating, so you will definitely hear from me in this regard very soon. Thanks. ❤️‍🩹

**Comment by emilyriederer** [comment] 2023-10-17 09:11
@BroVic - very sorry to hear that! Please don't stress about this or feel any pressure on the turnaround. Feel better soon!

**Comment by emilyriederer** [comment] 2023-11-11 01:38
Hi @BroVic ! I hope you are doing much better. I just wanted to check in and see when you thought you might be ready to circle back to this? Or do you think we should put it on pause?

**Comment by BroVic** [comment] 2023-11-16 16:24
Hello @emilyriederer. I'm sorry for the late response. I must have missed the notification.  No, I will make my submission in the next few days. And thanks for enquiring into my health. I'm fully recovered now.

**Comment by BroVic** [comment] 2023-11-16 17:03
Hello @mcsiple, thank you very much for your review. It enabled me to effect several improvements and opened my eyes to other issues you didn't mention directly. 

I have 2 comments:

1. I am aware that `sapply` is not type-safe, but in this case I would plead that we let it be as it is. The places where it is used are not accessible to the end user - those are utility files for generating some of the package's internal data. I had to use the function because I can return a named object and I made sure it returns a list via the `simplify = FALSE` argument. The other option would have been to use the {purrr}  package, but I don't believe this justified adding the dependency. If I tried, using other functions, everything just broke. 
2. Unfortunately, there is no canonical source for the correct versions of the administrative region names. Even the Nigerian Constitution, where the Local Government Areas are listed, overt mistakes as well as contested names! Right now, they are working on a law that addresses these naming discrepancies, and this is one of the things that made me develop this package in the first place. So, it's still evolving and when we have something more concrete, I will definitely implement your suggestion.

Once again, thanks!

**Comment by emilyriederer** [comment] 2023-11-22 11:02
Hi @cagrigokcek and @mcsiple - apologies for the delayed timeline on this review cycle! If you have the bandwidth to pull your mind back to this project, I'd really appreciate your thoughts on @BroVic 's comments above.

**Comment by mcsiple** [comment] 2023-11-25 15:16
Hi @BroVic and @emilyriederer , sorry for the delay. I was out of the office for a longer period than usual and am just getting back to my emails and GitHub. @BroVic , I am fine with those two comments. For (1) I agree that it's not worth adding a dependency (and I think `purrr` is sometimes slower than `sapply()`) so that is okay. And for (2) I am impressed at the ways you have found to include this 'naming flexibility' in your package. That is an exciting software challenge indeed  🙂

Anyway, I am satisfied with the changes and your comments.

**Comment by emilyriederer** [comment] 2023-11-27 01:46
Thanks so much @mcsiple ! I hope you had a nice break from the office.

If both you and @cagrigokcek could please use the [reviewer approval form](https://devguide.ropensci.org/approval2template.html) once you are satisfied, that will be the final step!

**Comment by cagrigokcek** [comment] 2023-11-28 01:51
Hi Emily, May I request a few days extension because I struggle with a severe tooth pain which decreases my concentration significantly? I promise to complete the form before the weekend.

Best.

Cagri

**Comment by emilyriederer** [comment] 2023-11-28 01:55
Of course, @cagrigokcek ! Sorry to hear that and please take the time that you need.

**Comment by BroVic** [comment] 2023-11-28 05:51
@cagrigokcek Sorry about your tooth. Do take care and get well soon.

**Comment by cagrigokcek** [comment] 2023-12-02 00:00
Hi viktor,

I am so sorry to see your message very late. I totally understand your situation about BrailleR package. As you said, it can be a further goal for you to develop packages which can be integrated with available packages related to accessibility in R later. I find your explanation very legitimate. Please don’t hesitate to reach me out when you need a tester in the future about features related to accessibility in R.

Best.

Cagri

**Comment by cagrigokcek** [comment] 2023-12-02 00:10
Hi Emily and Viktor,

I copy my review approval form below. Please let me know if there is any missing part in the form. 

I congratulate Viktor again. 

Best.

Cagri

 

- [X ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

 



 

Estimated hours spent reviewing: 5h30m

**Comment by emilyriederer** [comment] 2023-12-02 03:03
Congratulations @BroVic ! It looks like both reviewers have approved your package. (@mcsiple - would appreciate if you could fill out the last template just to close the loop, but I appreciate that we have your answer!) I will trigger the Approval bot now. Please review the messages it sends carefully with instructions for next steps to onboard this package to the rOpenSci family

**Comment by emilyriederer** [comment] 2023-12-02 03:03
@ropensci-review-bot approve najiR

**Closed by emilyriederer** 2023-12-02 03:03 UTC
Labels: 6/approved

**Comment by mcsiple** [comment] 2023-12-02 08:27
Oh and here's the form in case you need it:
## Reviewer Response


#### Final approval (post-review)

- [X] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**



Estimated hours spent reviewing: 5.5

**Comment by BroVic** [comment] 2023-12-05 12:26
@ropensci-review-bot finalize transfer of BroVic/naijR

**Comment by BroVic** [comment] 2023-12-05 12:54
Thank you @emilyriederer!
