### ISSUE TITLE
qualtdict: Generating Variable Dictionaries and Labelled Data Exports of Qualtrics Surveys

### ISSUE THREAD

**Issue by lyh970817** [ropensci/software-review#572] opened 2023-02-02 15:33 UTC
Submitting Author Name: Yuhao Lin
Submitting Author Github Handle: @lyh970817
Repository:  https://github.com/lyh970817/qualtdict
Version submitted: 0.0.0.9000
Submission type: Standard
Editor: @maurolepore
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: qualtdict
Title: Generating Variable Dictionaries and Labelled Data Exports of Qualtrics
    Surveys
Version: 0.0.0.9000
Authors@R:
    person("Yuhao", "Lin", , "yuhao.lin@kcl.ac.uk", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0001-6357-5731"))
Description: Provides functions that generate variable dictionaries from
    'Qualtrics' <https://www.qualtrics.com/about/> surveys and labelled
    survey data based on the dictionary. This package is built upon the R
    package 'qualtRics' <https://github.com/ropensci/qualtRics/> which
    provides access to 'Qualtrics' survey data and metadata via the 'Qualtrics' API
    <https://api.qualtrics.com/>.
License: MIT + file LICENSE
URL: https://github.com/lyh970817/qualtdict
BugReports: https://github.com/lyh970817/qualtdict/issues
Imports:
    crul,
    dplyr,
    glue,
    haven,
    magrittr,
    openNLP,
    purrr,
    qualtRics,
    rlang,
    sjlabelled,
    slowraker,
    SnowballC,
    stringi,
    stringr,
    tibble,
    tidyr,
    xml2
Suggests:
    covr,
    knitr,
    rmarkdown,
    testthat (>= 3.0.0),
    vcr (>= 0.6.0)
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Config/testthat/start-first: dict_generate, dict_validate, get_survey_data
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
	- [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

[Qualtrics](https://www.qualtrics.com/) is an online survey and data collection software platform. While the [qualtRics](https://github.com/ropensci/qualtRics) R package implements data retrieval from the Qualtrics platform, this package 'qualtdict' further processes its output to generate variable dictionaries and labelled data designed to be used for data analyses directly.  

-   Who is the target audience and what are scientific applications of this package?

The target audience is those who use the Qualtrics survey platform to collect data. This package generates variable dictionaries and labelled data designed to be used for data analyses directly.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No, but there is the similar [qualtRics](https://github.com/ropensci/qualtRics) R package that retrieves a broader range of data from Qualtrics than this package utilises. The output formats from qualtRics are much less user-friendly, for example, it retrieves survey metadata in a nested-list, json-like format, while this package rearranges essential parts of this metadata (retrieved using quatRics) into a publishable variable dictionary in a table format that can be visually inspected in, for example, excel.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes.

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by maurolepore** [comment] 2023-02-07 19:37
Dear @lyh970817, FYI I'm still searching for a handling editor. It shouldn't take much longer. Thanks for your patience.

**Comment by lyh970817** [comment] 2023-02-09 07:58
> Dear @lyh970817, FYI I'm still searching for a handling editor. It shouldn't take much longer. Thanks for your patience.

Thank you so much!

**Comment by maurolepore** [comment] 2023-02-11 10:59
@ropensci-review-bot assign @maurolepore as editor

**Comment by maurolepore** [comment] 2023-02-11 11:14
Dear @lyh970817 I'm delighted to announce that I'll be the handling editor of this submission. 

- [ ] I'll review the check results. If I see good opportunities to make reviewer's work easier I'll let you know.
- [ ] Can you please suggest three reviewers? Following our [guidelines](https://devguide.ropensci.org/editorguide.html#where-to-look-for-reviewers) I'll use one at most, but I would like your view of the types of expertise needed to review qualtdict.

**Comment by lyh970817** [comment] 2023-02-11 13:21
> Dear @lyh970817 I'm delighted to announce that I'll be the handling editor of this submission.
> 
> ### Semantic tags for my comments
> To help you track my comments I tagged them with "ml" and numbered sequentially: ml01, ml02, and so on. Comments following bullets are for you to consider -- you may or may not respond to them. Comments following check-boxes are requests for some action -- please respond.
> 
> ### Reviewers
> * [ ]  ml01. Can you please suggest three reviewers? Following our [guidelines](https://devguide.ropensci.org/editorguide.html#where-to-look-for-reviewers) I'll use one at most, but I would like your view of the types of expertise needed to review qualtdict.
> 
> ### Checks
> Here I list a few things that caught my attention. They are not blockers but the sooner we address them the better.
> 
> Package Dependencies
> 
> * ml02. Some imported packages appear to have no associated function calls; please ensure with author that these 'Imports' are listed appropriately.
> 
> `goodpractice` and other checks
> 
> * ml03. R CMD check generated the following check_fail: no_import_package_as_a_whole
> * ml04. Avoid library() and require() calls in packages: 1 time

ml01. Unfortunately I'm not sure if I could name any specific authors. But expertise-wise I thought having someone with a psychology/social science background might be helpful. As `qualtdict`  is centred around creating a variable dictionary giving an intuitive overview of survey data for analysts. The usefulness of such a dictionary is probably best judged by someone who analyses such data on a daily basis (in contrast to a data engineer who implements APIs for such data).

ml02. R CMD Check seems to fail without importing some of the packages that I don't actually use. For instance, without importing `haven`:
```r
Error in `set_labels_helper(x = .dat, labels = labels, force.labels = forc
e.labels, 
    force.values = force.values, drop.na = drop.na, var.name = NULL)`: Pac
kage 'haven' required for this function. Please install it.
```    
ml03. I use `dplyr`, `purrr` and `stringr` extensively so I import them as a whole. Should I still import functions from them (which will be many) individually?

ml04. I think it comes from this line in the tests:
```r
library(vcr) # *Required* as vcr is set up on loading
```
which is mandatory for `vcr` to work.

**Comment by maurolepore** [comment] 2023-02-12 21:55
* ml02. Following your example with the haven package I saw you need to import `haven::read_xpt` because the sjlabelled package needs it. That surprises me. Usually each package must import any external function it needs, and not as users to do it. Do you know why that's the case? Also I see haven is listed in .pre-commit.config.yaml -- which I'm not familiar with. So likely there is a good explanation and I just happen to never have encounter a case like this. It would be good to articulate an explanation because reviewers might be surprised too.

* ml03. Yeah, AFAIK best practice is to either namespace each function each time you call it or import each function individually. For example, each time use something like `dplyr::filter()` or import it once  with `usethis::use_import_from("dplyr", "filter")` then use it each time just like `filter()`.

* ml04. I see. Thanks!

- [ ] ml05. When tests run I see a lot of printed output. Please suppress it so that reviewers can see a succinct test report. If the output is not generated from an R condition (e.g. messages, warnings, or errors) it may be hard to suppress. See `capture.output()` -- you may need to implement a way to capture the output and maybe implement a `quietly` argument you can set to `TRUE` during tests.

- [ ] ml06. The test results I see show many warnings. Please address them if you don't expect them or suppress them if you do expect them. If you expect them it's best to make them go away so that you don't develop the habit of ignoring them and risk missing an important one that you don't expect.

```
[ FAIL 0 | WARN 591 | SKIP 0 | PASS 4 ]
```

- [ ] Can you please make your project an RStudio project? Most R developers/contributors work in RStudio. Without an .Rproj file launching the project is hard, and I would like reviewers to enter your package as smoothly as possible. You may use `usethis::use_rstudio()`. And later it may help to lower the entry-barrier for contributors.

**Comment by maurolepore** [comment] 2023-02-13 11:03
ml02. Thanks for explaining. The best solution will likely vary for each of the "unused" packages. 

In the case of heaven, the file you showed me has a single call of the type `haven::<some function>` so it might be worth looking at the source code of that function and see if you can re-implement it and remove the dependency on haven. 

https://github.com/strengejacke/sjlabelled/blob/548fa397bd013ec7e44b225dd971d19628fdc866/R/set_labels.R#L325

More generally, I think a great explanation of the trade-offs in dependencies is that of Jim Hester in his talk "It depends": https://www.youtube.com/watch?v=mum13N7CGUI . So as long as you understand those trade-offs you would be able to make an informed decision for each "unused" package and justify your decision if the reviewers ask.

**Comment by maurolepore** [comment] 2023-04-30 17:03
Dear @lyh970817, 
Just checking. Would you be available to address the comments ml05-ml07? We can also put this submission on hold if you need more time. Let me know.

**Comment by lyh970817** [comment] 2023-05-06 06:07
> Dear @lyh970817, 
> 
> Just checking. Would you be available to address the comments ml05-ml07? We can also put this submission on hold if you need more time. Let me know.

Yes, sorry - would just need a couple more days to address these. Thanks.

**Comment by maurolepore** [comment] 2024-01-07 19:16
@ropensci-review-bot put on hold

**Comment by maurolepore** [comment] 2024-04-08 22:10
@lyh970817, how would you like to proceed? 

1. Follow up on https://github.com/ropensci/software-review/issues/572#issuecomment-1537062517
2. Continue on hold.
3. Withdrawal the submission. 

> The holding status will be revisited every 3 months, and after one year the issue will be closed.
-- https://devdevguide.netlify.app/softwarereview_policies.html#policiesreviewprocess

**Comment by maurolepore** [comment] 2024-06-19 14:28
Dear @lyh970817

I hope all is well. I totally understand priorities change. At this moment I believe this policy applies:

> If the author hasn’t requested a holding label, but is simply not responding, we should close the issue within one month after the last contact intent. This intent will include a comment tagging the author, but also an email using the email address listed in the DESCRIPTION of the package which is one of the rare cases where the editor will try to contact the author by email.
-- https://devdevguide.netlify.app/softwarereview_policies

FYI my next step is to confirm with the chief editor and if they agree I'll close the issue and let you know by email.

**Comment by maurolepore** [comment] 2024-06-20 15:23
Dear @lyh970817 I confirmed with the chief editor and shared my next steps with the entire editorial board. I'll go ahead and close this issue and let you know by email.

Once again, I understand priorities change. Thank a lot for contributing to rOpenSci. We look forward to more contributions whenever it's a good time.

**Closed by maurolepore** 2024-06-20 15:23 UTC
Labels: holding, 1/editor-checks
