### ISSUE TITLE
unifir: A Unifying API for Working with Unity in R

### ISSUE THREAD

**Issue by mikemahoney218** [ropensci/software-review#521] opened 2022-03-24 22:53 UTC
**Date accepted:** 2022-05-01

Submitting Author Name: Mike Mahoney
Submitting Author Github Handle: @mikemahoney218
Repository:  https://github.com/mikemahoney218/unifir
Version submitted: 0.1.0
Submission type: Standard
Editor: @melvidoni
Reviewers: @vinhtantran, @wjones127

Due date for @vinhtantran: 2022-04-20
Due date for @wjones127: 2022-04-29

Archive: TBD
Version accepted: TBD

Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: unifir
Title: A Unifying API for Calling 'Unity' from R
Version: 0.1.0
Authors@R: 
    person("Michael", "Mahoney", , "mike.mahoney.218@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0003-2402-304X"))
Description: Functions for the creation and manipulation of scenes and objects
    within the 'Unity' '3D' video game engine (<https://unity.com/>). Specific
    focuses include the creation and import of terrain data and 'GameObjects' as
    well as scene management.
License: MIT + file LICENSE
Depends:
    R (>= 3.5.0)
Imports: 
    glue,
    methods,
    proceduralnames,
    R6,
    utils
Suggests: 
    terrainr,
    covr,
    knitr,
    lintr,
    pkgdown,
    rmarkdown,
    styler,
    testthat (>= 3.0.0),
    terra,
    sf
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.2
Config/testthat/edition: 3
Config/testthat/parallel: true
URL: https://mikemahoney218.github.io/unifir/, https://github.com/mikemahoney218/unifir
BugReports: https://github.com/mikemahoney218/unifir/issues
VignetteBuilder: knitr

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [x] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
Following discussion in #508, I believe this package is within scope for the following reason:

This package provides bindings to the Unity video game engine API from R, for the production of 3D/VR "environments" entirely from R code. It enables producing a new type of visualization in an efficient and reproducible manner, and provides specific methods for visualizing spatial data stored in standard spatial formats. However, I could understand if the package itself is too general for rOpenSci in particular; while we are designing it for research applications, Unity is not explicitly scientific software.

-   Who is the target audience and what are scientific applications of this package?

The target audience is anyone looking to produce data-driven immersive virtual environments in Unity, with a primary focus on visualizing natural environments. I work directly with ecologists and landscape architects, and so the initial feature set is oriented towards making the package useful for that audience.

Immersive virtual environments are an active area of research (see for instance https://www.mm218.dev/papers/vrs_2021.pdf, https://joss.theoj.org/papers/10.21105/joss.04060, https://link.springer.com/article/10.1007/s42489-020-00069-6 ). At the moment, the current standard for the field is producing hand-designed "artistic" environments tailored for each purpose, which makes assessing this visualization method difficult. Our aim with this project is to produce a standard set of tooling for creating immersive virtual environments, making it both easier to produce visualization "bases" for applications and giving us a way to produce reproducible visualizations as a baseline for assessing visualization effectiveness directly.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I'm not aware of any. The closest is likely the rayverse (rayshader/rayrender), which makes fantastic 3D visualizations in R directly, without incorporating Unity; the incorporation of Unity makes adding player controllers (for interactive exploration of the environment) much easier.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

#508 

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

x These functions do not have examples: [check_debug, create_if_not].

These functions are not exported, which given my past experiences with CRAN implies that they should not have examples (as apparently examples are run for non-exported functions on test machines).

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by mikemahoney218** [comment] 2022-03-24 22:54
While it's not relevant to this issue, I do wonder if `has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.` should be updated to remove Travis now that rOpenSci recommends moving away from Travis?
https://devguide.ropensci.org/ci.html?q=travis#travis-ci-linux-and-mac-osx

**Comment by jooolia** [comment] 2022-03-29 06:22
@ropensci-review-bot assign @melvidoni  as editor

**Comment by jooolia** [comment] 2022-03-29 07:17
@ropensci-review-bot assign @melvidoni as editor

**Comment by melvidoni** [comment] 2022-03-29 20:17
@ropensci-review-bot seeking reviewers

**Comment by melvidoni** [comment] 2022-04-08 00:17
@ropensci-review-bot assign @wjones127 as reviewer

**Comment by vinhtantran** [comment] 2022-04-16 17:34
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   **Briefly describe any working relationship you have (had) with the package authors.** None
-   ☒ As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

#### Documentation

The package includes all the following forms of documentation:

-   ☒ **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
-   ☒ **Installation instructions:** for the development version of package and any non-standard dependencies in README
-   ☒ **Vignette(s):** demonstrating major functionality that runs successfully locally
-   ☒ **Function Documentation:** for all exported functions
-   ☒ **Examples:** (that run successfully locally) for all exported functions
-   ☒ **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

-   ☒ **Installation:** Installation succeeds as documented.
-   ☒ **Functionality:** Any functional claims of the software been confirmed.
-   ☒ **Performance:** Any performance claims of the software been confirmed.
-   ☒ **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
-   ☒ **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 8 hours

-   ☒ Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer (“rev” role) in the package DESCRIPTION file.

------------------------------------------------------------------------

### Review Comments

I am not a Unity user or game developer, so I have to rely to the *“Why do this?”* section in the README to understand why the package is needed. The author pointed out two motivations: the use of closed-source tooling in current research and the potential of bias for personal preference. The first motivation is intriguing in that the package has the potential to encourage researchers to publish open-source and reproducible source codes for their studies. However, I hope the author can elaborate on the second point in terms of how the package would assist with the aforementioned issue.

The source code was well-written and packaged. I have nothing to say about how the code was written and structured. It’s not surprising given that this is not the author’s first submission to rOpenSci.

The vignettes are simple to follow and put into action. By following the 102 vignette, I was able to create a toy working example in Unity. I understand that the CRAN check and GitHub actions limit your ability to showcase more sophisticated examples with your assets, but I’d love to see one that highlights all package’s features, perhaps from a blogpost? It’s only a suggestion.

Another point I’d like to make is about the package’s ongoing development. I cloned the package and wrote a bunch of comments on some inconsistencies in your function documentation a few weeks ago, only to discover that the majority of them have been fixed in your most recent commits, which were made a few days ago. Although the majority of them are minor changes, I would recommend that you include a note in the Review report to let us reviewers know which version we should work on.

Finally, congratulations on a job well done. The review process taught me a lot, including new information about the R6 object in R.

I’ve included some detailed comments below. Some of them may be obsolete in your most recent commit because I did not have time to revise them all.

#### Detailed Comments

-   Function documentation:
    -   Include a link to the referred function in the Descriptions, such as the reference to `instantiate_prefab()` in `add_default_player()`.
    -   Make use of fixed width font in Markdown by putting in \` \` pairs when referring to function and argument names.
    -   The object names displayed are not consistent. For example, in `add_texture()`, it states “A ‘unifir\_script’ object”, then in `add_prop()`, it states “A \[unifir\_prop\] object”.
    -   All sentences in “Description” should end with a period.
    -   `find_unity()` Description is mixed with Details. They are not continuous. Either move everything to the Description or the Details sections.
-   Vignettes:
    -   I was able to follow the vignettes step-by-step and helped me understand the package and its purpose because I have not known Unity before.
    -   The `library(unifir)` in the setup chunk at top of the pages should be hidden (`echo = FALSE`). Readers should see it right before the first call to the package’s function, similar to what you have in “Unifir 101”, instead of out of nowhere at the top of the pages.
    -   The notice of usage of `waiver()` and others to ensure rendering on CRAN could be put in the comment on top of the function call instead of the text below the code. Also, make sure to note all those “blank code”. You miss one `waiver()` notice at Action section of 102.
-   Function Examples:
    -   `get_asset()` calls `add_players()` which is no longer available in the latest commit.
-   Packaging Guidelines:
    -   I’d suggest removing ‘from R’ from the Title to avoid error when publishing to CRAN.

**Comment by mikemahoney218** [comment] 2022-04-16 18:37
Thank you so much @vinhtantran ! I apologize for having you review a "moving target" -- I was doing a standard update across all my packages and completely forgot this one should be "frozen". I'll follow up with fixes and replies once our other review is in!

**Comment by wjones127** [comment] 2022-04-25 22:32
I'm about half-way through my review, but in the meantime I've posted an issue in the repo:

 * https://github.com/mikemahoney218/unifir/issues/4

**Comment by wjones127** [comment] 2022-04-26 18:07
Added two other issues:

 * https://github.com/mikemahoney218/unifir/issues/6
 * https://github.com/mikemahoney218/unifir/issues/7

**Comment by wjones127** [comment] 2022-04-26 19:50
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples:** (that run successfully locally) for all exported functions
- [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing:

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

Overall this package is very good. The code style and level of testing are excellent.

I worked through the vignettes successfully, and then tried to create a simple scene of my own. I've reported the major issues I encountered in that process, which I think ought to be addressed (most already have 💯 ):

* https://github.com/mikemahoney218/unifir/issues/4
* https://github.com/mikemahoney218/unifir/issues/6
* https://github.com/mikemahoney218/unifir/issues/7
* https://github.com/mikemahoney218/unifir/issues/8

In addition, I noticed a few smaller issues while reviewing the package:

* [ ] `find_unity()` docs are a little funny: the enumerated list is pushed down to details, so it's a little confusing.
* [ ] The readme doesn't have linked to the vignettes, though that is suggested in the rOpenSci guidelines.
* [ ] By default, `add_default_tree()` adds trees that are 90 degrees from vertical.

**Comment by melvidoni** [comment] 2022-04-26 21:28
Thank you @vinhtantran and @wjones127 for the reviews!
Please, @mikemahoney218 keep us posted on how you are advancing with this.

**Comment by mikemahoney218** [comment] 2022-04-26 21:47
Will do! I've got a feature branch with changes in response to these reviews open at https://github.com/mikemahoney218/unifir/pull/5 , and I expect to have addressed all comments in the near future -- I'll update here once I've done so. 

Thanks everyone!

**Comment by mikemahoney218** [comment] 2022-04-28 18:14
Hi all! I believe I've addressed all reviewer comments in a branch on the unifir repo, https://github.com/mikemahoney218/unifir/tree/response_to_reviewers (diff at https://github.com/mikemahoney218/unifir/pull/5/files , NEWS at https://github.com/mikemahoney218/unifir/blob/response_to_reviewers/NEWS.md ). Thank you so much for your comments, the package is looking a lot better as a result!

# Response to @vinhtantran

Thanks so much for your review! I'd like to include you in the DESCRIPTION as a reviewer -- would you be able to tell me what I should list for "given" and "family" names? I don't want to infer incorrectly!

## Function documentation

* [x] Include a link to the referred function in the Descriptions, such as the reference to instantiate_prefab() in add_default_player()
  * Believe this is now fixed, thanks!
* [x] Make use of fixed width font in Markdown by putting in ` ` pairs when referring to function and argument names. (AND) [x] The object names displayed are not consistent. For example, in add_texture(), it states “A ‘unifir_script’ object”, then in add_prop(), it states “A [unifir_prop] object”.
  * I've done another pass through all the function documentation to try and address this -- classes are now demarcated by ``, functions by [ (which should generate links), and I now attempt to always refer to both the relevant class and constructor function (so the given example now reads "A `unifir_script` object created by [make_script]" and "a `unifir_prop` object created by [unifir_prop]".
* [x] All sentences in “Description” should end with a period.
  * Fixed! Thanks for flagging.
* [x] find_unity() Description is mixed with Details. They are not continuous. Either move everything to the Description or the Details sections.
  * Whoops! Messed that up. Thanks for flagging.

## Vignettes

* [x] The library(unifir) in the setup chunk at top of the pages should be hidden (echo = FALSE). Readers should see it right before the first call to the package’s function, similar to what you have in “Unifir 101”, instead of out of nowhere at the top of the pages.
  * Fixed!
* [x] The notice of usage of waiver() and others to ensure rendering on CRAN could be put in the comment on top of the function call instead of the text below the code. Also, make sure to note all those “blank code”. You miss one waiver() notice at Action section of 102.
  * Done!

## Packaging guidelines

* [x] I’d suggest removing ‘from R’ from the Title to avoid error when publishing to CRAN.
  * Done! Thanks for flagging.
  

  
---

# Response to @wjones127

Thank you so much for your review! Below I'm only addressing the comments on this issue; I've dealt with the larger issues on their own tickets in the unifir repo. I'd like to include you in the DESCRIPTION as a reviewer, as well -- should I list you as Will Jones or something else?

* [x] `find_unity()` docs are a little funny: the enumerated list is pushed down to details, so it's a little confusing.
  * Fixed! Thanks. Guess I misunderstood how roxygen2 generates these sections.
* [x] The readme doesn't have linked to the vignettes, though that is suggested in the rOpenSci guidelines.
  * Fixed!
* [x] By default, `add_default_tree()` adds trees that are 90 degrees from vertical.
  * Fixed!

**Comment by melvidoni** [comment] 2022-04-28 22:54
Thanks for the response @mikemahoney218. @vinhtantran and @wjones127 can you please review the response and see if your comments were addressed?

**Comment by wjones127** [comment] 2022-04-29 16:11
@mikemahoney218 I can confirm that all my comments have been addressed. I left a few optional follow-up comments in my final review of the changes here: https://github.com/mikemahoney218/unifir/pull/5#pullrequestreview-957918764

Great work!

> I'd like to include you in the DESCRIPTION as a reviewer, as well -- should I list you as Will Jones or something else?

Yes, "Will Jones" is good to list me as. Email is willjones127 at gmail, if you need that.

**Comment by vinhtantran** [comment] 2022-04-29 21:31
All of my comments have been addressed. Great work @mikemahoney218.

> # Response to @vinhtantran
> Thanks so much for your review! I'd like to include you in the DESCRIPTION as a reviewer -- would you be able to tell me what I should list for "given" and "family" names? I don't want to infer incorrectly!

Please use "Tan Tran" with the email address of vinhtantran at GMail.

**Comment by melvidoni** [comment] 2022-05-01 20:12
Hello all @vinhtantran and @wjones127 thank you for  the review!

@mikemahoney218 since @wjones127 left a final review, please address that and let me know once it is done so I can approve..

**Comment by melvidoni** [comment] 2022-05-01 20:14
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/521#issuecomment-1110187724 time 8

**Comment by melvidoni** [comment] 2022-05-01 20:15
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/521#issuecomment-1100715168 time 8

**Comment by mikemahoney218** [comment] 2022-05-01 20:26
Hi @melvidoni ! All of the last changes have been made (all resolved as part of https://github.com/mikemahoney218/unifir/pull/5#pullrequestreview-957918764 and https://github.com/mikemahoney218/unifir/issues/7 ) so I believe we're all set here.

Thanks!

**Comment by melvidoni** [comment] 2022-05-01 20:53
@ropensci-review-bot approve unifir

**Closed by melvidoni** 2022-05-01 20:53 UTC
Labels: 6/approved

**Comment by mikemahoney218** [comment] 2022-05-01 20:56
@ropensci-review-bot finalize transfer of unifir

**Comment by mikemahoney218** [comment] 2022-05-01 20:58
@melvidoni I'm not sure if there's an expected lag, but I don't appear to have been added to the unifir team (and as such don't yet have admin on the repo)

**Comment by melvidoni** [comment] 2022-05-01 21:32
Hello @mikemahoney218. You'll have to wait so I can ask about the bot. I believe it should have created the group.
Give me a couple days, please.

**Comment by mikemahoney218** [comment] 2022-05-01 21:33
No worries! It did create the team -- https://github.com/orgs/ropensci/teams/unifir -- but didn't add me. I'm on the terrainr team ( https://github.com/orgs/ropensci/teams/terrainr ) so I don't believe there's any issue with my MFA setup. No rush at all!

**Comment by maelle** [comment] 2022-05-02 05:55
I had to approve you, weird, I'm exploring. In any case you've now been added to the team @mikemahoney218!

**Comment by mikemahoney218** [comment] 2022-05-02 09:14
Awesome, thanks @maelle ! In case it helps debugging, I manually requested access to the team after the bot didn't add me, I didn't get added without approval. 

I believe that means the repo is transferred and we're all good to go! Thank you so much everyone!

**Comment by maelle** [comment] 2022-05-02 10:06
You might the first "repeat" submitter since we started using the bot, we'll investigate. Thanks for catching this bug and your patience :grin:
