### ISSUE TITLE
gitlabr

### ISSUE THREAD

**Issue by jirkalewandowski** [ropensci/software-review#113] opened 2017-04-26 04:04 UTC
### Summary

-   What does this package do? (explain in 50 words or less):

`gitlabr` provides access to the API of the project and repository management software [gitlab](https://about.gitlab.com/). Files, issues, comments, etc. can be read and modified from R through gitlabr on either your self-hosted installation of gitlab or the public gitlab.com.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: gitlabr
Title: Access to the Gitlab API
Version: 0.9
Authors@R: person("Jirka", "Lewandowski", email = "jirka.lewandowski@wzb.eu", role = c("aut", "cre"))
Description: Provides R functions to access the API of the project and
    repository management web application gitlab. For many common tasks (repository
    file access, issue assignment and status, commenting) convenience wrappers
    are provided, and in addition the full API can be used by specifying request
    locations. Gitlab is open-source software and can be self-hosted or used on
    gitlab.com.
Depends:
    R (>= 3.1.2),
    magrittr
Imports:
    dplyr (>= 0.4.3),
    stringr,
    base64enc,
    httr (>= 1.1.0),
    purrr (>= 0.2.2),
    tibble (>= 1.1),
    utils,
    yaml
Suggests:
    devtools (>= 1.8.0),
    roxygen2,
    testthat (>= 1.0.2),
    R.rsp,
    knitr,
    shiny (>= 0.13.0)
URL: https://blog.points-of-interest.cc/post/gitlabr/ http://doc.gitlab.com/ce/api/
BugReports: https://gitlab.points-of-interest.cc/points-of-interest/gitlabr/issues/
VignetteBuilder: R.rsp
License: GPL (>= 3)
LazyData: true
RoxygenNote: 5.0.1
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/jirkalewandowski/gitlabr

-   Who is the target audience?

People who use R in a team that uses gitlab for code and/or data hosting and/or project management.

-   Are there other R packages that accomplish the same thing? If so, what is different about yours?

There is [gh](https://github.com/r-pkgs/gh) providing similar things for Github.com, but Gitlab has a free & open source self-hosting variant and is used internally by many organizations, including academics.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration with Travis CI and/or another service.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  *It already is on CRAN.*
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package contains a [`paper.md`](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? Please describe any exceptions: *The package does not use covr, since the test suite seems to fail in the environment covr creates. I'm very happy to discuss this and/or get help with fixing. See the branch [codecov](https://github.com/jirkalewandowski/gitlabr/tree/codecov)*

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by noamross** [comment] 2017-04-28 15:10
Thank you for the submission, @jirkalewandowski!  This package fits under our reproducibility category.  A few small things before we assign reviewers:

1) We generally move accepted packages into the rOpenSci organization upon acceptance. We do this for several reasons, primarily so that we can do testing, serve rOpenSci packages through our API, and also so we can chip in maintenance if authors fall behind. Our few exceptions have been when the package is already under the umbrella of another group, such as Bioconductor, that serves the same role. If accepted, we'd like to set up a way to at least mirror to the rOpenSci organization.

2) We would strongly prefer that the package be hosted in its installable state, meaning that it includes NAMESPACE, documentation, etc., even if those are generated by *roxygen2*.

3) Could you provide some developer-aimed documentation on the minimum setup needed to run the tests locally such as env variables and acquiring appropriate tokens? (In a `CONTRIBUTING.md` file would be appropriate). I plan to have both an experienced and a new gitlab user as reviewers (I myself am the latter), and this will also make it easier gitlab novices assist with the *covr* issue and run our other checks.

**Comment by jirkalewandowski** [comment] 2017-05-02 11:47
Dear @noamross, thank you for taking care of this submission and your remarks.

ad 1. Sounds great, we could move the jirkalewandowski/gitlabr github project to the ropensci organization then. Since the github repo is a mirror of the development repo on https://gitlab.points-of-interest.cc anyways, there is no need for the jirkalewandowski/gitlabr repo in addition to ropensci.

ad 2. & 3. Sounds also great. I'll take of both issues within the next two weeks and post back here.

**Comment by jirkalewandowski** [comment] 2017-05-12 14:05
Dear @noamross, I added the roxygen-generated files to the github repository and a CONTRIBUTING.md with the requested information.

**Comment by noamross** [comment] 2017-05-12 14:40
Thank you @jirkalewandowski!

I've run goodpractice::gp() (skipping **covr** checks).  Here are the results.  None of them are major/mandatory but should be considered guidance for yourself and the reviewers.  

── GP gitlabr ───────────────────────────

It is good practice to

  ✖ not use "Depends" in DESCRIPTION, as it can cause name clashes, and poor interaction with other packages. Use "Imports" instead.
  ✖ avoid long code lines, it is bad for readability. Also, many people prefer editor windows that are about 80 characters wide. Try make your lines shorter than 80 characters

    R/ci.R:12:1
    R/ci.R:26:1
    R/ci.R:33:1
    R/ci.R:36:1
    R/ci.R:41:1
    ... and 101 more lines

  ✖ avoid sapply(), it is not type safe. It might return a vector, or a list, depending on the input data. Consider using vapply() instead.

    R/ci.R:38:41

  ✖ not import packages as a whole, as this can cause name clashes between the imported packages. Instead, import only the specific functions you need.
──────────────────────────────────────────────
`devtools::spell_check()` yielded to real hits:

**Comment by noamross** [comment] 2017-05-12 14:47
@rmflight @jennybc As part of your review please look into the *covr* issue. If it's not clear to you what the issue is we can call in some additional expertise.

**Comment by noamross** [comment] 2017-06-02 12:03
@rmflight @jennybc A friendly reminder that you reviews are due in one week.

**Comment by rmflight** [comment] 2017-06-02 15:49
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions in R help (see comments below)
- [ ] **Examples** for all exported functions in R Help that run successfully locally
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and `URL`, `Maintainer` and `BugReports` fields in DESCRIPTION 

>##### Paper (for packages co-submitting to JOSS)
>
>The package contains a `paper.md` with:
>
>- [ ] **A short summary** describing the high-level functionality of the software
>- [ ] **Authors:**  A list of authors with their affiliations
>- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
>- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines


#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 

---

### Review Comments

The package `gitlabr` provides a comprehensive interface to the **gitlab** API, enabling many different **gitlab** operations
from the `R` command line to any http reachable **gitlab** server for which an individual has credentials. This interface
appears to be very useful for anyone wishing to interact with a **gitlab** server from `R`. The breadth of functionality is
impressive, with functions even for creating **CI** files based on a particular template. It appears also that it is already being used
by some in the `R` community besides the author, given the number of downloads / month from CRAN.

Specific areas of concern that need to be addressed are below.

#### README

The README does not follow the packaging guidelines from **ropensci**, however most of the information requested is present
with the exception of a **statement of need**, which could be copied from the DESCRIPTION file.

```
* The package name
* Badges for continuous integration and test coverage (and any other badges)
* Short description of the package
* Installation instructions
* Example usage
```

#### Vignette

- the **quick-start-gitlabr** vignette does not use *generic* code or code that would successfully run in the setup chunk. To enable
this the author should consider having a very generic example with completely fictional *server*, *username* and *password*, and then 
**hide** a chunks that is really run to enable output in the examples. 
- the **quick-start-gitlabr** vignette seems more like a full vignette, one section of which is a **quick-start** guide. The author 
should consider either breaking the vignette into two, or re-titling the current vignette and making the quick-start just a sub-section.
- For either approach, the quick start could still use some actual commentary on what the code is doing outside of comments in the code blocks.
- Under **central features**, before API calls, a better explanation of **how** the base object is instantiated would be appreciated.
- For a quick start, the author might consider highlighting the *set style* **first**, as this is probably the easiest method and the 
one that new users are likely to be most familiar with. The other two styles would then be illustrated as more *functional* in nature
and useful for managing several connections simultaneously.

#### Function Documentation

- function `gl_list_branches` has **List create and delete branches** 3 times
- not sure that `gl_repository` and `gl_list_files` ... belong together in documentation.
- Why do some functions have parameters that are **ignored**?? See `gl_get_project_id` for example.
- in contrast to other exported functions that deal with **projects**, `gl_proj_req` seems out of place. Should it be 
`gl_project_request` instead??
- `gl_connection` documentation and the **vignette** are out of sync with respect to the version of the default API version, one says 
**v3** is default, other says **v4** is default.

#### Examples

In almost all cases, the examples are not code that would actually run without setup first. I understand the reason for this, it is
working with a web-service. However, one potential solution is to do something like:

```r
## Not run
my_connection <- gl_connection(....)
set_gitlab_connection(my_gitlab)
function_being_documented
```

with the example in `\dontrun{}` in the `roxygen2` documentation. Or if the author does not agree with the `set_gitlab_connection`, then one of the other styles. The point is that the examples should fully runnable on a **gitlab** instance somewhere after copying and pasting the code, even if it doesn't run otherwise.

Some functions that have no examples include:
- `gl_*_issue`
- `gl_create_merge_request`

- Comments on **why** certain parameters are set to what they are would also be appreciated in the examples.

In addition, for the `gl_*_ci` functions, some explanation of **how** changing parameters will change the resuling `*.yml` file would
really help. Even in the example field, having a the function call and then the output would be useful. Or this may be where a vignette
just on CI would be a good thing to do. But current documentation of the CI functions (besides pushing the file) are not very clear or 
useful.

#### Automated Tests

- testing setup documentation is in `Contributing.md`, and the code seems to work.
- I was able to run `covr::package_coverage(type = "tests")` by moving the **environment.yml** file to the **testthat** directory, putting the setting of variables at the top of `test_branches`, and disabling the first test in `test_ci`. See [my fork](https://github.com/rmflight/gitlabr/tree/rmfligth_review)
- For `test_ci`, I tried a couple of different solutions, but neither worked. Not sure why. 
- Overall, test coverage seems pretty good at 49%, with some of the code not being tested for good reasons, such as resulting in writing 
to the test gitlab repo, or using an interactive Shiny module.


#### Packaging Guidelines

- **Code duplication**:
  - `gl_connection` and `gl_project_connection` seem to be almost duplicates outside
  of the `project` argument and call to `to_project_id`, seems that `project = NULL` could be used 
  in `gl_connection` and then checked and set appropriately instead of having two separate functions?
  - `http_error_or_content`: without looking in here, can't tell that `ct` is content, thought it was count. Sometimes variable names are too short to be truly informative **where** they are used (eg in `gitlab`).
- **Lack of comments**. There is not a single code comment in any of the source
  code files outside of the `roxygen2` function documentation. Although **much** of the code is self-explanatory and easy to 
  follow, some
  of it (`gitlab` especially) is not easy to follow. Some comments on the non-exported
  functions would be very useful, or the author should consider use the `@noRd` tag to document in source
  using `roxygen2` but not generate Rd files.

**Comment by sckott** [comment] 2017-06-02 16:08
thx @rmflight ! est. hrs spent reviewing?

**Comment by rmflight** [comment] 2017-06-02 16:10
sorry @sckott . Was thinking that would be at the very end, assuming examining changes that are made. Fixed!

**Comment by sckott** [comment] 2017-06-02 16:15
good point, there is some amount of additional reviewer time in the conversation following the review

**Comment by jennybc** [comment] 2017-06-19 07:55
Just checking in to say I'm working on this review.

**Comment by jennybc** [comment] 2017-07-11 03:49
## Package Review

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions in R help
- [ ] **Examples** for all exported functions in R Help that run successfully locally
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 6

---

### Review Comments

Overall, I'm excited by this package and think it has a really interesting design. It provides both high- and low-level functions for interacting with the gitlab API. It's largely well-constructed, with idiomatic R code and very thorough documentation and explanation of the important design features.

I was impressed that I could run the test suite with a modest amount of tweaking and knowledge. However my main concern right now is that I can't do simple things with the gitlab.com API. I haven't dug deep enough to tell if there's a problem with gitlabr itself or with its documentation, which is causing user error. I can make basic requests using "raw" httr, so it doesn't appear to be a fatal problem with my gitlab.com account. I note there are no examples or tests against gitlab.com, which feels like an oversight. I think functionality and/or documentation has gotten over-tuned against the author's gitlab instance.

#### Documentation

**A statement of need**

This is not *explicitly* done in the README. However, this is definitely present in other places. It would be good to add 1-2 sentences to README.

**Vignette(s)**

I have run the vignette code that is not `eval = FALSE`, after substituting my own username and password. My main concern is that I cannot run equivalent code against gitlab.com (more below).

**Examples**

Many functions lack examples. I wouldn't expect universal example coverage, in any event, but more examples would be good.

#### Functionality

**Functionality:**

I have not been able to run basic code against gitlab.com. I *can* run essentially all code I see in tests, vignette, etc. against gitlab.points-of-interest.cc. It's not clear if this is a real problem or a documentation problem, leading to user error. Either way, it needs to be addressed.

It would probably be best if examples, README, etc. featured gitlab.com, as most users would probably be doing that. It might also reveal now or in the future if there is some underlying problem that I am experiencing.

For example, here's code adapted from the examples in `gl_connection()`:

```r
my_gitlab <- gl_connection(
  "https://gitlab.com",
  private_token = Sys.getenv("GITLAB_PVT_TOKEN")
)
my_gitlab("projects")
```

First, the `gl_connection()` call needs to specify the name of the second argument or else it's interpreted as the `login`. Second, the `my_gitlab()` call hangs indefinitely for me. 

**Automated tests:**

I was able to run tests for this package without too much pain, which is pretty impressive, so big kudos for that! I have yet to write tests for an API-wrapping package that achieves this worthy goal. Some thoughts and suggestions:

  * Why test against your gitlab server vs gitlab.com? It's not completely hard-wired, given the URL in `environment.yml` but I suspect there would be some undocumented setup required if I actually changed the target gitlab server.
  * The instructions don't tell me how to populate `environment.yml`. Where do I get this info on gitlab? Is the token supposed to be the private token displayed in the account tab of user settings or an access token generated from the access tokens tab?
  * Once I populate `environment.yml` with real info, I should `.gitignore` it, right? That would be good to clarify. If testing on CI, then I assume there's an encryption strategy for this file. Or maybe secure env vars are used?
  * Each test file should use `context("blah blah")` at the top for nicer reporting. I've done this is my review branch.
  * I had to `skip()` the test about issue editing, because I don't have necessary permission. Would be good to implement this such that tester is editing an issue they have permission on. Again, pretty impressive that it's the *only* test I had to skip!  I've done this is my review branch.
  * [These lines re: API version in `testthat.R`](https://github.com/jirkalewandowski/gitlabr/blob/3525479b1316abd2f2122f7778be2c3c4f8b3d06/tests/testthat.R#L4-L14) are pretty unusual. I can't infer the exact goal, but wonder if there's a better / more conventional way to achieve it. Obviously, I understand it's got something to do with testing against different API versions.
  * I've moved common env var setup into `helper.R` and out of individual test files. Looking at the top of these files, I suspect even more setup could probably be similarly centralized? `helper.R` is always sourced by `devtools::load_all()` so this makes for a nice workflow even when developing / running tests interactively, i.e. the info doesn't *need* to live in each file.

**Packaging guidelines**:

I recommend use of `README.Rmd`. I find this makes it much harder for `README.md` to slowly drift out of sync with what the package actually does.

I needed to explicitly qualify `purrr::set_names()` to pass `R CMD check`.

As mentioned above, many functions do not have an example.

Package dependencies. Re: the pipe `%>%` and friends: I advise to move magrittr from "Depends" to "Imports". You can then import individual operators that are used. In my review branch, I've done this.
  
#### Other notes

**dplyr dependency**: I would seriously consider NOT depending on dplyr. I realize this might be highly impractical. But if dplyr can be removed with modest effort, it might be worth it. dplyr is more end-user facing and not optimized for use within other packages, whereas tibble and purrr are designed with this usage in mind.
  
**rprojroot**: [rprojroot](https://cran.r-project.org/web/packages/rprojroot/index.html) might be useful for hardening path formation, e.g., below `tests/`. Or even testthat offers some support for same. Paths like `yaml::yaml.load_file("../../.gitlab-ci.yml")` have a way of breaking. However, I acknowledge the current strategy must be working pretty well, since gitlabr is pretty mature.

**Deprecated functions**: Currently the deprecated functions dominate the function index. I wonder if ... you could `@keyword` these `internal` in order to keep them around but suppress their inclusion here?

**Tibbles of results**: For `gl_list_projects()` (and perhaps others): could you hoist `name` and `name_with_namespace` to the front for human readability?

#### Things I did not check

I did not have time to look into the covr issue.

**Comment by jirkalewandowski** [comment] 2017-07-11 15:18
Dear @jennybc @rmflight -- thank you very much for the detailed reviews! I learned several things already from reading and will start implementing the changes you suggest over the next months, as I see how this will improve the package in many respects.

**Comment by jennybc** [comment] 2017-07-11 15:20
I thought more about my experience and what I learned yesterday about the differences between gitlab and GitHub: gitlab lets you see all public projects and regards them as "yours" when you list. Coupled with automatic pagination, this is why `gl_list_projects()` hangs indefinitely for me on gitlab.com. Who knows how many projects its trying to retrieve?

If I limit to one page, I do succeed:

``` r
library(gitlabr)
my_gitlab <- gl_connection(
  gitlab_url = "https://gitlab.com",
  private_token = Sys.getenv("GITLAB_PVT_TOKEN")
)
my_gitlab(gl_list_projects, page = 1)
#> # A tibble: 20 x 50
#>         id
#>      <chr>
#>  1 3683998
#>  2 3683931
#>  3 3683891
#>  4 3683865
#>  5 3683855
#>  6 3683853
#>  7 3683770
#>  8 3683767
#>  9 3683766
#> 10 3683753
#> 11 3683719
#> 12 3683693
#> 13 3683669
#> 14 3683665
#> 15 3683664
#> 16 3683657
#> 17 3683651
#> 18 3683640
#> 19 3683628
#> 20 3683617
#> # ... with 49 more variables: description <chr>, archived <chr>,
#> #   visibility <chr>, ssh_url_to_repo <chr>, http_url_to_repo <chr>,
#> #   web_url <chr>, owner.name <chr>, owner.username <chr>, owner.id <chr>,
#> #   owner.state <chr>, owner.avatar_url <chr>, owner.web_url <chr>,
#> #   name <chr>, name_with_namespace <chr>, path <chr>,
#> #   path_with_namespace <chr>, container_registry_enabled <chr>,
#> #   issues_enabled <chr>, merge_requests_enabled <chr>,
#> #   wiki_enabled <chr>, jobs_enabled <chr>, snippets_enabled <chr>,
#> #   created_at <chr>, last_activity_at <chr>,
#> #   shared_runners_enabled <chr>, lfs_enabled <chr>, creator_id <chr>,
#> #   namespace.id <chr>, namespace.name <chr>, namespace.path <chr>,
#> #   namespace.kind <chr>, namespace.full_path <chr>, import_status <chr>,
#> #   star_count <chr>, forks_count <chr>, open_issues_count <chr>,
#> #   public_jobs <chr>, only_allow_merge_if_pipeline_succeeds <chr>,
#> #   request_access_enabled <chr>,
#> #   only_allow_merge_if_all_discussions_are_resolved <chr>,
#> #   approvals_before_merge <chr>, default_branch <chr>,
#> #   forked_from_project.id <chr>,
#> #   forked_from_project.http_url_to_repo <chr>,
#> #   forked_from_project.web_url <chr>, forked_from_project.name <chr>,
#> #   forked_from_project.name_with_namespace <chr>,
#> #   forked_from_project.path <chr>,
#> #   forked_from_project.path_with_namespace <chr>
```

So I think this (at least) is a documentation issue, but a pretty important one. Perhaps there should be a page limit of last resort, as well, to prevent an attempt to retrieve all public projects on gitlab, for example.

**Comment by noamross** [comment] 2017-07-11 18:13
Thank you for your reviews, @jennybc and @rmflight! @jirkalewandowski, do keep us posted on your progress and don't hesitate to ask questions of your reviewers here.

**Comment by noamross** [comment] 2017-08-15 21:48
@jirkalewandowski Just checking in on the status of your updates. Do you have an expected time frame for revision?

**Comment by noamross** [comment] 2017-09-18 11:38
Hello @jirkalewandowski - I wanted to check in again on your plans for this package. Do you have an expected date where you'll respond to reviews with your updates?

**Comment by jirkalewandowski** [comment] 2017-09-18 12:38
Dear @noamross, thanks for the reminders and sorry for the late response, I've been offline for a while. My plan is to incorporate the feedback in October, most likely in combination with packing together gitlabr 1.0, the first version that will no longer support the old API v3, but only v3.

**Comment by noamross** [comment] 2017-12-10 00:45
Hello @jirkalewandowski, are you still planning to complete this review process?

**Comment by noamross** [comment] 2019-02-25 20:09
Closing this submission as it has been dormant for > 1 yr.  Authors may re-submit if they would like to continue the process.

**Closed by noamross** 2019-02-25 20:09 UTC
Labels: 4/review(s)-in-awaiting-changes, holding, package, topic:data-access, topic:reproducibility

**Comment by statnmap** [comment] 2020-08-12 15:54
I'd like to help in finishing this process. Indeed, the maintainer passed away last year, so I decided to take over the development of this package but I am not sure to find time and resources to do it alone.  
I did not had the opportunity to know Jirka. I am just a recent user of his package.  

I already cloned the original Github repository and started accounting for @jennybc comments: https://github.com/statnmap/gitlabr/  
I cloned it in a way to allow issues on the repository, there is no link to the original repository.  

I think the Readme is now closer to a direct reproducible example, provided that the user has a token.  
Now there is obviously some needs in the vignette, functions examples and unit tests as also pointed by @rmflight . 
And there is a need to upgrade according to last {tibble} and {dplyr} versions. I wrote a fix, but did not went deep into it.  

I will try to continue the process, but it is difficult to find some time on it.  
Can I find some help among rOpenSci developers? Could you use your network to ask for collaboration?

**Comment by noamross** [comment] 2020-08-12 21:25
Hello @statnmap.  We're saddened to hear of the maintainer's passing.  We are encouraged to hear you are interested in updating and maintaining the package and would be glad to help find you some support.   Can you provide an email so we can invite you to our Slack workspace where we'll ping for volunteers?

**Comment by statnmap** [comment] 2020-08-12 21:44
Sure. You can send the invitation here: sebastien@thinkr.fr  
Thanks.

**Comment by statnmap** [comment] 2020-08-14 07:32
I joined the Slack workspace. Thanks.   
I take my 3 weeks vacation and when I come back, we'll ping for volunteers.  
I'll have to open some issues first to define what is to be done.
