### ISSUE TITLE
Submission: {cffr} Generate Citation File Format ('cff') Metadata for R Packages

### ISSUE THREAD

**Issue by dieghernan** [ropensci/software-review#463] opened 2021-09-16 14:14 UTC
Submitting Author Name: Diego Hernangómez
Submitting Author Github Handle: @dieghernan
Repository: https://github.com/dieghernan/cffr
Version submitted: 0.0.1.9001 
Submission type: Standard
Editor:  @emilyriederer 
Reviewers: @sckott, @zambujo
Due date for @sckott: 2021-10-19
Due date for @zambujo: 2021-10-20
Archive: TBD
Version accepted: TBD

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: cffr
Title: Generate Citation File Format ('cff') Metadata for R Packages
Version: 0.0.1.9001
Authors@R: 
    person(given = "Diego",
           family = "Hernangómez",
           role = c("aut", "cre"),
           email = "diego.hernangomezherrero@gmail.com",
           comment = c(ORCID = "0000-0001-8457-4658"))
Description: The Citation File Format version 1.2.0 (Druskat, S. et al.
    (2021) <doi:10.5281/zenodo.5171937>) is a human and machine readable
    file format which provides citation metadata for software. This
    package provides core utilities to generate and validate this
    metadata.
License: GPL (>= 3)
URL: https://dieghernan.github.io/cffr/,
    https://github.com/dieghernan/cffr
BugReports: https://github.com/dieghernan/cffr/issues
Depends: 
    R (>= 3.6.0)
Imports: 
    crayon (>= 1.4.1),
    desc (>= 1.3.0),
    jsonlite (>= 1.7.2),
    jsonvalidate (>= 1.1.0),
    yaml (>= 2.2.1)
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: 
    knitr
Config/testthat/edition: 3
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
X-schema.org-keywords: attribution, citation, credit, citation-files, cff,
    metadata
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [x] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

The package extract metadata from DESCRIPTION and CITATION and generates a [CITATION.cff file](https://citation-file-format.github.io/).

CITATION.cff files are plain text files with human- and machine-readable citation information for software (and datasets).

-   Who is the target audience and what are scientific applications of this package?

Any R package developer. A CITATION.cff file provides clarity when citating R packages. [GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files), [Zenodo](https://twitter.com/ZENODO_ORG/status/1420357001490706442) and [Zotero](https://twitter.com/zotero/status/1420515377390530560) supports this format.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

[**{citation}**](https://github.com/pik-piam/citation/): The development version (at the time of this writing) includes a new function `r2cff` that creates a minimal `CITATION.cff` file (v1.1.0) using the information of your  `DESCRIPTION` file. It also provide minimal validity checks.

[**{handlr}**](https://github.com/ropensci/handlr): Tool for converting among citation formats, including `*.cff` files. At the time of
  this writing only CFF v1.1.0 was supported (see [#24](https://github.com/ropensci/handlr/issues/24)).

**{cffr}** performs an extensive extraction of DESCRIPTION and CITATION, as well as validation via **{jsonvalidate}** against the 
official [schema.json](https://github.com/citation-file-format/citation-file-format/blob/main/schema.json). None of the packages mentioned before supports CFF v1.2.0, that is the latest released version. 

It also provides parsers for `person` and `citation/bibentry` classes.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

N/A

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

https://github.com/ropensci/software-review/issues/462 @noamross 

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by noamross** [comment] 2021-09-16 17:36
Thanks, @dieghernan! @emilyriederer will be your editor.   FYI, our check-bot failed because the `<!--repourl--><!--end-repourl-->` tags were absent from your submission template. I've added them back in.  We're looking into ways to make that more robust!

**Comment by dieghernan** [comment] 2021-09-16 17:44
My bad, thank you!

**Comment by emilyriederer** [comment] 2021-09-17 02:02
Hi @dieghernan - so nice to meet you and thank you for submitting this great package! 

I did not notice any causes for concern on my first review, and the only enhancement found by the testing suite is perhaps splitting up a few of the long lines of code found by [`lintr`](https://github.com/jimhester/lintr). You can run `lintr::lint_package(".")`  within your R package to reproduce these locally. 

I think we are ready to move to the next stage, so I will begin to look for reviewers. We will be in touch soon!

**Comment by dieghernan** [comment] 2021-09-17 09:08
Thanks @emilyriederer , nice to meet you as well.

I did my best trying to remove long lines of code, most of them were links to long urls, but I managed to get no lint warning on that, see:

https://github.com/dieghernan/cffr/actions/runs/1244840358

I also added the badge to the README, thanks for the `rodev::use_review_badge(463)`

(PS: I was looking for images of neural networks and I found that fantastic .png 😄 )

**Comment by dieghernan** [comment] 2021-09-17 14:05
@ropensci-review-bot check package

**Comment by noamross** [comment] 2021-09-17 14:22
@ropensci-review-bot check package

**Comment by emilyriederer** [comment] 2021-09-17 23:04
Thanks, @dieghernan ! 

One other metric I just wanted to call out is the high cyclocomplexity scores for `clean_str()` and `cff_create()`.  

If you aren't familiar with this score (I wasn't until this review!), the R package's [README](https://github.com/MangoTheCat/cyclocomp) gives some good examples. In short, it measure how many different distinct paths your code might go through when evaluation (based on things like `if-else` clauses). Right now, our checks highlight scores greater than 15. High scores might suggest opportunities for simplification with strategies like using more internal helper functions; high scores can also suggest that the function is hard to test robustly since it can be hard to hit all the corner cases.

I want to say upfront, **I am comfortable with your code as-is and think these functions are very reasonable**. For your functions, all of the blocks seem necessary and so concise that more internal functions might actually decrease the readability of the code.

That said, I thought I'd also highlight that part of the review for your judgement. 

Still working on the reviewers but hope to have some news soon!

**Comment by dieghernan** [comment] 2021-09-17 23:39
Thanks @emilyriederer, I would have a look on that. I still don’t fully understand the high score on `clean_str` (24 loc with 3 if/else, would investigate it).

I would like to highlight that I have implemented a strategy with `testthat` + GHA for testing the package on >5000 packages. More information here: 
- https://github.com/dieghernan/cffr/tree/main/tests/testthat/test_ci

Latest results here:

- https://github.com/dieghernan/cffr/actions/runs/1247163030

I have used this for detecting  corner cases, but probably this have added also complexity on the functions.

The tests are OK now, and in the packages that the validation is failing are due to errors on the raw files of the packages tested (i.e. malformed urls and DOI/ORCID on old packages, that won’t be compliant with the current CRAN policies).

Thanks for your hard work. May I suggest for review any of the authors of {codemeta} or {handlr} (both in rOpenSci)? The scope of these packages are closely related with {cffr} and it will be interesting to have their feedback.

**Comment by dieghernan** [comment] 2021-09-18 00:27
I @emilyriederer , I have introduced some changes and removing some unneeded chunks (https://github.com/dieghernan/cffr/commit/1aeb1868b8c3989fe8e9e9b438a7d99658270034)

Now running `cyclocomp::cyclocomp_package_dir()` I see:

|   |name                          | cyclocomp|
|:--|:-----------------------------|---------:|
|7  |cff_create                    |        13|
|17 |cff_write                     |        11|
|9  |cff_parse_citation            |        10|
|10 |cff_parse_person              |         8|
|19 |clean_str                     |         8|
|6  |cff                           |         7|
|35 |parse_desc_urls               |         6|
|42 |rapply_cff                    |         6|
|1  |as.cff                        |         5|
|16 |cff_validate                  |         5|
|39 |parse_r_citation              |         5|
|23 |is.substring                  |         4|
|3  |building_month                |         3|
|5  |building_url                  |         3|
|18 |clean_jsonlite                |         3|
|22 |is.email                      |         3|
|24 |is.url                        |         3|
|25 |merge_desc_cit                |         3|
|32 |parse_desc_keywords           |         3|
|2  |building_doi                  |         2|
|14 |cff_schema_keys               |         2|
|21 |is.cff                        |         2|
|29 |parse_desc_authors            |         2|
|31 |parse_desc_date_released      |         2|
|37 |parse_package_meta            |         2|
|38 |parse_preferred_auto          |         2|
|43 |stopifnotcff                  |         2|
|44 |stopifnotexists               |         2|
|4  |building_other_persons        |         1|
|8  |cff_description               |         1|
|11 |cff_schema_definitions_entity |         1|
|12 |cff_schema_definitions_person |         1|
|13 |cff_schema_definitions_refs   |         1|
|15 |cff_schema_keys_license       |         1|
|20 |drop_null                     |         1|
|26 |other_persons                 |         1|
|27 |other_persons_entity          |         1|
|28 |parse_desc_abstract           |         1|
|30 |parse_desc_contacts           |         1|
|33 |parse_desc_license            |         1|
|34 |parse_desc_title              |         1|
|36 |parse_desc_version            |         1|
|40 |print.cff                     |         1|
|41 |print_snapshot                |         1|
|45 |validate_schema               |         1|

**Comment by emilyriederer** [comment] 2021-09-28 02:30
@ropensci-review-bot add @sckott to reviewers

**Comment by emilyriederer** [comment] 2021-09-28 02:32
@ropensci-review-bot add @sckott to reviewers

**Comment by dieghernan** [comment] 2021-09-28 09:32
Hi @sckott , nice to meet you. I just wanted to say hello and let you know that some days ago I added a new vignette "Crosswalk" that provides tecnical details and examples on how {cffr} extracts the metadata. I think this may be useful:

https://dieghernan.github.io/cffr/articles/crosswalk.html

Regards

**Comment by emilyriederer** [comment] 2021-09-29 09:53
@ropensci-review-bot add @zambujo to reviewers

**Comment by emilyriederer** [comment] 2021-09-29 09:55
Thanks to @sckott and @zambujo for volunteering to review!

**Comment by zambujo** [comment] 2021-10-29 20:41
Hi @emilyriederer: @dieghernan thoroughly addressed all of my comments and suggestions. Great job!

**Comment by sckott** [comment] 2021-10-29 21:37
✅ @dieghernan has addressed my comments, nice work 🚀

**Comment by emilyriederer** [comment] 2021-10-30 18:45
Approved! Congratulations, @dieghernan, for the great work, and thanks to @zambujo and @sckott  for your thoughtful reviews! :tada:

To-dos:
- [ ] Transfer the repo to rOpenSci's "ropensci" GitHub organization under "Settings" in your repo.  I have invited you to a team that should allow you to do so.  You'll be made admin once you do.
- [ ] Fix all links to the GitHub repo to point to the repo under the ropensci organization.
- [ ] Delete your current code of conduct file if you had one since rOpenSci's default one will apply, see https://devguide.ropensci.org/collaboration.html#coc-file
- [ ] If you already had a `pkgdown` website **and are ok relying only on [rOpenSci central docs building and branding](https://devguide.ropensci.org/ci.html#even-more-ci-ropensci-docs)**,
    * deactivate the automatic deployment you might have set up
    * remove styling tweaks from your pkgdown config but keep that config file
    * replace the whole current `pkgdown` website with a [redirecting page](https://devguide.ropensci.org/redirect.html)
    * replace your package docs URL with `https://docs.ropensci.org/package_name`
    * In addition, in your DESCRIPTION file, include the docs link in the `URL` field alongside the link to the GitHub repository, e.g.: `URL: https://docs.ropensci.org/foobar (website) https://github.com/ropensci/foobar`
- [ ] Fix any links in badges for CI and coverage to point to the ropensci URL. We no longer transfer Appveyor projects to ropensci Appveyor account so after transfer of your repo to rOpenSci's "ropensci" GitHub organization the badge should be `[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/ropensci/pkgname?branch=master&svg=true)](https://ci.appveyor.com/project/individualaccount/pkgname)`. If Appveyor does not pick up new commits after transfer, you might need to delete and re-create the Appveyor project. (Repo transfers are smoother with GitHub Actions)
- [ ] Please check you updated the package version post-review version updated and that you documented all changes in NEWS.md
- [ ] We're starting to roll out software metadata files to all ropensci packages via the Codemeta initiative, see https://github.com/ropensci/codemetar/#codemetar for how to include it in your package, after installing the package - should be easy as running codemetar::write_codemeta() in the root of your package.

Should you want to acknowledge your reviewers in your package DESCRIPTION, you can do so by making them `"rev"`-type contributors in the `Authors@R` field (with their consent).  More info on this [here](https://devguide.ropensci.org/building.html#authorship).


Welcome aboard! We'd love to host a post about your package - either a [short introduction to it with an example](https://ropensci.org/tech-notes/) for a technical audience or [a longer post with some narrative about its development or something you learned, and an example of its use](https://ropensci.org/blog/) for a broader readership. If you are interested, consult [the blog guide](https://blogguide.ropensci.org/), and tag @stefaniebutland in your reply. She will get in touch about timing and can answer any questions.

We've put together an online book with our best practice and tips, [this chapter](https://devguide.ropensci.org/collaboration.html) starts the 3d section that's about guidance for after onboarding. Please tell us what could be improved, the corresponding repo is [here](https://github.com/ropensci/dev_guide).

**Closed** 2021-10-30 18:46 UTC
Labels: 6/approved, topic:peer-reviewed

**Comment by emilyriederer** [comment] 2021-10-30 18:53
@dieghernan , I know I shared a *lot* in the message above, so I wanted to highlight one more specific item for your consideration. I think this package could be of very high interest to the rOpenSci community since it would apply generally across all domains. If you'd be interested in thinking about how this package could be highlighted in an rOpenSci blog post or [tech note](https://ropensci.org/technotes/), it might be worth having a discussion with @ropensci/blog-editors

I think it could be great to highlight how this package is similar in spirit to well-known tools like `devtools` and `usethis` and smartly reuses repository context to create a general-purpose citation file. This could also help raise awareness for GitHub's citation feature and the benefits that you see in it since it is relatively new.

**Comment by dieghernan** [comment] 2021-10-31 17:50
Hi @emilyriederer, thanks! I am not able to transfer the repo, could you please double check? I’ll answer the rest of the comment on a later stage

**Comment by emilyriederer** [comment] 2021-11-01 01:03
Hi @dieghernan - my apologies. You should have now received an invitation to join a team within the `ropensci` organization. Please accept that and try the transfer. After it is complete, I will go in and make you an admin on the transferred repo.

**Comment by dieghernan** [comment] 2021-11-01 05:08
Repo transferred @emilyriederer!  By the way, the rOpenSci badge is still as "Under Review" (?)

[![peer-review](https://badges.ropensci.org/463_status.svg)](https://github.com/ropensci/software-review/issues/463)

Also ping @noamross

**Comment by emilyriederer** [comment] 2021-11-01 10:00
Admin access granted!

**Comment by stefaniebutland** [comment] 2021-11-01 15:53
Hi @dieghernan, I'm rOpenSci's Community Manager. Congratulations on cffr passing review! Yes a post noted by Emily would be really valuable. Narrative and technical guidelines are in https://blogguide.ropensci.org/. If you're interested, please suggest when you would like to submit a draft. I recognize this is extra work, so no pressure intended here :-)

My colleague @steffilazerte would review it and suggest a publication date.

**Comment by dieghernan** [comment] 2021-11-02 19:23
Hi @stefaniebutland, @steffilazerte

I’ll have a look and let you know a feasible date for the blog post. 

I was also thinking on submitting the package to CRAN, and I wonder if submitting it before or after you publish the post. The package is almost ready for it.

What are your views on this? Regards

**Comment by stefaniebutland** [comment] 2021-11-02 20:47
I can't think of a specific reason to choose publishing before or after CRAN (Steffi how about you?). It's up to you. We could have your post in a pull request, reviewed and ready to publish once on CRAN if you prefer that.

**Comment by steffilazerte** [comment] 2021-11-02 21:10
I think it's up to you as well. I can't imagine that CRAN would have you change anything major that would affect the user experience, and we generally have you link to the ropensci docs page (not to the CRAN page), so it shouldn't matter in the blog post.

**Comment by dieghernan** [comment] 2021-11-04 16:25
Hi @steffilazerte @emilyriederer 

I think I could send a draft post by the end of the next week. So assuming at least one week for reviewing and that the posts are usually published on Tuesday (as per the [Blogguide](https://blogguide.ropensci.org/content.html) the first feasible publishing date would be **Nov. 23 2021**. 

Let me know what you think,

Regads

**Comment by stefaniebutland** [comment] 2021-11-04 19:02
Just fyi, @maelle & others wrote this post in Feb 2021: [Make Your R Package Easier to Cite](https://ropensci.org/blog/2021/02/16/package-citation/). So you know what rOpenSci has said on the topic before. 

Steffi and I agreed Nov 23 is a good tentative publication date.

**Comment by dieghernan** [comment] 2021-11-05 00:29
And it is on CRAN! https://cran.r-project.org/package=cffr

**Comment by emilyriederer** [comment] 2021-11-06 17:52
Congratulations, @dieghernan ! That's fantastic news!
